//! Boa harness: boots a JS context per file and walks the test tree.

use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::time::Instant;

use boa_engine::builtins::promise::PromiseState;
use boa_engine::object::builtins::{JsArray, JsPromise};
use boa_engine::{Context, JsError, JsValue, Module, Source};

use zero_runtime::ZERO_DOM_SHIM_BODY;
use zero_transpile::{TranspileOptions, transpile_typescript};

use crate::loader::{CoverageContext, ZeroModuleLoader};
use crate::result::{Failure, FileResult, SourceLoc, Status, TestOutcome};

/// Combined return from [`run_file_with_coverage`]: the file's outcomes plus
/// (when coverage is enabled) a JSON snapshot of `globalThis.__zero_coverage__`,
/// and the canonical paths the loader resolved during this run.
pub struct RunOutcome {
    pub result: FileResult,
    pub coverage: Option<serde_json::Value>,
    /// Sorted, deduped list of every canonical path the loader resolved while
    /// evaluating this file. Used by `zero mutate` to build a per-test-file
    /// import set for test-impact analysis.
    pub loaded: Vec<PathBuf>,
}

/// Framework-internal runtime module basenames; frames whose path basename is
/// in this set are skipped when picking the topmost user frame from a stack.
const FRAMEWORK_INTERNAL_BASENAMES: &[&str] = &[
    "test.js",
    "template.js",
    "reactivity.js",
    "app.js",
    "router.js",
    "dom-shim.js",
    "http.js",
];

/// Function names that identify test-framework registration call sites.
/// A frame whose function name is one of these is never the actual throw
/// site — it's the call that *contains* the throw. The stack walker skips
/// these when picking the topmost user frame, so a raw `TypeError` (or any
/// non-matcher throw) doesn't get pinned to the `it(...)` registration line.
const FRAMEWORK_REGISTRATION_NAMES: &[&str] = &[
    "it",
    "describe",
    "beforeEach",
    "afterEach",
    "beforeAll",
    "afterAll",
    "cleanup",
    "render",
];

/// A thrown JS error captured from Boa, with stack and user-frame metadata.
struct CapturedError {
    message: String,
    stack: Option<String>,
    user_frame: Option<String>,
}

/// Remap `file.ts:LINE:COL` positions in a Boa error string back to their
/// original TypeScript source positions using a source map generated by SWC.
///
/// Without source maps, Boa reports positions in the transpiled JS while
/// attributing them to the original `.ts` filename — producing misleading line
/// numbers. This corrects them so stack-frame lines point at the actual
/// TypeScript source.
fn remap_positions(error: &str, sm: Option<&sourcemap::SourceMap>) -> String {
    let sm = match sm {
        Some(s) => s,
        None => return error.to_string(),
    };
    // Match absolute paths ending in .ts followed by :LINE:COL
    let re = regex::Regex::new(r"([^\s()]+\.ts):(\d+):(\d+)").expect("valid regex");
    re.replace_all(error, |caps: &regex::Captures| {
        let path = &caps[1];
        let line: u32 = caps[2].parse().unwrap_or(1);
        let col: u32 = caps[3].parse().unwrap_or(1);
        // sourcemap crate uses 0-based line/col; Boa reports 1-based
        match sm.lookup_token(line.saturating_sub(1), col.saturating_sub(1)) {
            Some(tok) => {
                let orig_line = tok.get_src_line() + 1;
                let orig_col = tok.get_src_col() + 1;
                format!("{path}:{orig_line}:{orig_col}")
            }
            None => format!("{path}:{line}:{col}"),
        }
    })
    .into_owned()
}

/// Run all tests in `file_abs` and return the collected outcomes.
///
/// # Parameters
/// - `project_root`: absolute path to the project root (used for module resolution).
/// - `file_abs`: absolute path to the test file to run.
///
/// # Returns
/// A [`FileResult`] with all outcomes and any load error.
pub fn run_file(project_root: &Path, file_abs: &Path) -> FileResult {
    run_file_with_coverage(project_root, file_abs, None).result
}

/// Run `file_abs` with a pre-built loader. Used by `zero mutate` to inject a
/// per-mutant overlay of mutated source.
pub fn run_file_with_loader(
    project_root: &Path,
    file_abs: &Path,
    loader: Rc<ZeroModuleLoader>,
) -> FileResult {
    run_with_loader(project_root, file_abs, loader, false).result
}

/// Like [`run_file`] but optionally enables coverage instrumentation. When
/// `coverage` is `Some`, the loader instruments in-scope source files; after
/// the test loop, `globalThis.__zero_coverage__` is serialized to JSON and
/// returned alongside the result.
pub fn run_file_with_coverage(
    project_root: &Path,
    file_abs: &Path,
    coverage: Option<Rc<CoverageContext>>,
) -> RunOutcome {
    let want_coverage = coverage.is_some();
    let loader = match coverage {
        Some(ctx) => Rc::new(ZeroModuleLoader::new_with_coverage(project_root, ctx)),
        None => Rc::new(ZeroModuleLoader::new(project_root)),
    };
    run_with_loader(project_root, file_abs, loader, want_coverage)
}

fn run_with_loader(
    project_root: &Path,
    file_abs: &Path,
    loader: Rc<ZeroModuleLoader>,
    want_coverage: bool,
) -> RunOutcome {
    let rel_path = file_abs
        .strip_prefix(project_root)
        .unwrap_or(file_abs)
        .to_path_buf();
    let rel_for_panic = rel_path.clone();
    let project_root_owned = project_root.to_path_buf();
    let file_abs_owned = file_abs.to_path_buf();

    // Swap in a silent panic hook for the duration of catch_unwind so a
    // teardown panic doesn't dump a stderr trace before the synthetic failure
    // is reported. The guard restores the original hook on drop, even if the
    // closure itself panics.
    let _hook_guard = SilentPanicHookGuard::install();

    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        run_with_loader_inner(
            &project_root_owned,
            &file_abs_owned,
            loader,
            want_coverage,
            rel_path,
        )
    }));
    drop(_hook_guard);

    match result {
        Ok(outcome) => outcome,
        Err(payload) => synthesize_panic_outcome(rel_for_panic, payload),
    }
}

fn run_with_loader_inner(
    project_root: &Path,
    file_abs: &Path,
    loader: Rc<ZeroModuleLoader>,
    want_coverage: bool,
    rel_path: PathBuf,
) -> RunOutcome {
    let mut context = match build_js_context(loader.clone()) {
        Ok(c) => c,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    install_console(&mut context);
    install_workspace_file_reader(&mut context, project_root);
    if let Err(f) = eval_dom_shim(&mut context) {
        return load_error_outcome(rel_path, f);
    }
    let raw = match read_test_source(file_abs) {
        Ok(s) => s,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    let (src, ts_source_map) = match prepare_source(raw, file_abs) {
        Ok(out) => out,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    loader.register_path(
        &file_abs.to_string_lossy(),
        file_abs.parent().unwrap_or(project_root),
    );
    let module = match parse_test_module(&src, file_abs, &mut context) {
        Ok(m) => m,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    if let Err(f) = evaluate_module(&module, &mut context) {
        return load_error_outcome(rel_path, f);
    }
    let root = match get_test_tree_root(&loader, &mut context) {
        Ok(v) => v,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    let mut outcomes = Vec::new();
    walk_describe(
        &root,
        &mut Vec::new(),
        &mut outcomes,
        ts_source_map.as_ref(),
        &mut context,
    );

    // Test-only injection point for the catch_unwind safety net: force a
    // panic *after* tests have run and outcomes are collected but before
    // teardown. Mirrors the Boa MapLock-finalizer panic that the safety
    // net is designed to convert into a structured failure.
    #[cfg(test)]
    if tests::should_force_teardown_panic() {
        panic!("forced teardown panic for test");
    }

    let coverage_value = if want_coverage {
        serialize_coverage(&mut context)
    } else {
        None
    };
    let loaded = loader.loaded_paths();
    // Leak the Boa context instead of dropping it. Dropping (or
    // `gc::force_collect()`-ing) runs Boa 0.21.1's `MapLock::finalize`
    // (boa_engine/.../map/ordered_map.rs), which `downcast_mut`s the backing
    // map during GC finalization and panics with `Object already borrowed:
    // BorrowMutError` whenever a `Map` is still locked at collection time. That
    // first panic then trips a *second* panic in a destructor during unwind,
    // producing a non-unwinding abort that bypasses the `catch_unwind` net in
    // `run_with_loader` and kills the whole process — so a single test file
    // using `Map` can abort the entire suite (see FRAMEWORK_NOTES #63).
    //
    // We never need this file's heap again: each file gets a fresh context, the
    // process is short-lived, and coverage was already serialized above. Leaking
    // skips the buggy finalizers entirely. The cost is per-file memory growth
    // (~12 MB/file); bounded by suite size and acceptable for a test run. The
    // real fix lives upstream (Boa's own `TODO: try_downcast_mut`).
    std::mem::forget(context);
    RunOutcome {
        result: FileResult {
            path: rel_path,
            outcomes,
            load_error: None,
        },
        coverage: coverage_value,
        loaded,
    }
}

type SilentHookState = std::sync::Mutex<(
    usize,
    Option<Box<dyn Fn(&std::panic::PanicHookInfo) + Sync + Send>>,
)>;

fn silent_hook_state() -> &'static SilentHookState {
    static STATE: std::sync::OnceLock<SilentHookState> = std::sync::OnceLock::new();
    STATE.get_or_init(|| std::sync::Mutex::new((0, None)))
}

/// RAII guard: replaces the panic hook with a no-op for the duration of
/// `catch_unwind` so the default stderr backtrace doesn't fire before the
/// synthetic failure is reported. Reference-counted via a process-global
/// mutex so concurrent guards (e.g. parallel `cargo test`) do not stomp on
/// each other's saved hook.
struct SilentPanicHookGuard;

impl SilentPanicHookGuard {
    fn install() -> Self {
        let mut guard = silent_hook_state()
            .lock()
            .expect("panic hook mutex poisoned");
        if guard.0 == 0 {
            let prev = std::panic::take_hook();
            std::panic::set_hook(Box::new(|_| {}));
            guard.1 = Some(prev);
        }
        guard.0 += 1;
        Self
    }
}

impl Drop for SilentPanicHookGuard {
    fn drop(&mut self) {
        let mut guard = silent_hook_state()
            .lock()
            .expect("panic hook mutex poisoned");
        if guard.0 == 0 {
            return;
        }
        guard.0 -= 1;
        if guard.0 == 0
            && let Some(prev) = guard.1.take()
        {
            std::panic::set_hook(prev);
        }
    }
}

/// Synthesize a structured `RunOutcome` for a panic caught from
/// [`run_with_loader_inner`]. Outcomes collected before the panic are lost
/// because the inner stack unwound — this is the accepted trade-off; a GC /
/// teardown panic is rare, and the synthetic failure makes the run loud
/// instead of crashing the process.
fn synthesize_panic_outcome(
    rel_path: PathBuf,
    payload: Box<dyn std::any::Any + Send>,
) -> RunOutcome {
    let msg = panic_payload_to_string(payload.as_ref());
    RunOutcome {
        result: FileResult {
            path: rel_path,
            outcomes: vec![TestOutcome {
                name_chain: vec!["<Boa GC panic during teardown>".to_string()],
                status: Status::Failed,
                duration_ms: 0,
                failure: Some(Failure {
                    message: format!("Boa GC panic: {msg}"),
                    stack: None,
                    location: None,
                }),
            }],
            load_error: None,
        },
        coverage: None,
        loaded: vec![],
    }
}

fn panic_payload_to_string(p: &(dyn std::any::Any + Send)) -> String {
    if let Some(s) = p.downcast_ref::<&'static str>() {
        return (*s).to_string();
    }
    if let Some(s) = p.downcast_ref::<String>() {
        return s.clone();
    }
    "<non-string panic payload>".to_string()
}

/// Wrap a load-time `Failure` into an empty `RunOutcome` keyed by `rel_path`.
fn load_error_outcome(rel_path: PathBuf, failure: Failure) -> RunOutcome {
    RunOutcome {
        result: FileResult {
            path: rel_path,
            outcomes: vec![],
            load_error: Some(failure),
        },
        coverage: None,
        loaded: vec![],
    }
}

/// Build a Boa `Context` configured with the given module loader.
fn build_js_context(loader: Rc<ZeroModuleLoader>) -> Result<Context, Failure> {
    Context::builder()
        .module_loader(loader)
        .build()
        .map_err(|e| Failure {
            message: format!("failed to build JS context: {e}"),
            stack: None,
            location: None,
        })
}

/// Evaluate the framework DOM shim into the current context so that
/// `globalThis.document` and friends exist before user modules run.
fn eval_dom_shim(ctx: &mut Context) -> Result<(), Failure> {
    ctx.eval(Source::from_bytes(ZERO_DOM_SHIM_BODY.as_bytes()))
        .map(|_| ())
        .map_err(|e| js_err_to_failure(&e, ctx))
}

/// Read the on-disk test source.
fn read_test_source(file_abs: &Path) -> Result<String, Failure> {
    std::fs::read_to_string(file_abs).map_err(|e| Failure {
        message: format!("cannot read {}: {e}", file_abs.display()),
        stack: None,
        location: None,
    })
}

/// For `.ts` files transpile to JS and return a source map; for `.js` files
/// pass through unchanged.
fn prepare_source(
    raw: String,
    file_abs: &Path,
) -> Result<(String, Option<sourcemap::SourceMap>), Failure> {
    if file_abs.extension().and_then(|e| e.to_str()) != Some("ts") {
        return Ok((raw, None));
    }
    let logical = file_abs.to_string_lossy().into_owned();
    let out = transpile_typescript(
        &raw,
        &TranspileOptions {
            filename: &logical,
            inline_source_map: false,
            emit_source_map: true,
        },
    )
    .map_err(|e| Failure {
        message: format!("transpile error: {e}"),
        stack: None,
        location: None,
    })?;
    let sm = out
        .source_map
        .as_deref()
        .and_then(|j| sourcemap::SourceMap::from_slice(j.as_bytes()).ok());
    Ok((out.code, sm))
}

/// Parse the (already-transpiled) test source as an ES module.
fn parse_test_module(src: &str, file_abs: &Path, ctx: &mut Context) -> Result<Module, Failure> {
    Module::parse(
        Source::from_bytes(src.as_bytes()).with_path(file_abs),
        None,
        ctx,
    )
    .map_err(|e| js_err_to_failure(&e, ctx))
}

/// Load, link, and evaluate `module`; drive the job queue to completion and
/// surface any rejection as a `Failure`.
fn evaluate_module(module: &Module, ctx: &mut Context) -> Result<(), Failure> {
    let eval_promise = module.load_link_evaluate(ctx);
    let _ = ctx.run_jobs();
    if let PromiseState::Rejected(reason) = eval_promise.state() {
        return Err(js_val_to_failure(reason, ctx));
    }
    Ok(())
}

/// Pull the `__getTestTree__` export off the cached `zero/test` module and
/// invoke it to materialize the describe tree root.
fn get_test_tree_root(loader: &ZeroModuleLoader, ctx: &mut Context) -> Result<JsValue, Failure> {
    let test_mod = loader.get_cached("zero/test").ok_or_else(|| Failure {
        message: "zero/test module was not loaded by the test file".to_string(),
        stack: None,
        location: None,
    })?;
    let ns = test_mod.namespace(ctx);
    let get_tree = ns
        .get(boa_engine::js_string!("__getTestTree__"), ctx)
        .map_err(|e| js_err_to_failure(&e, ctx))?;
    get_tree
        .as_callable()
        .and_then(|f| f.call(&JsValue::undefined(), &[], ctx).ok())
        .ok_or_else(|| Failure {
            message: "__getTestTree__ is not callable or threw".to_string(),
            stack: None,
            location: None,
        })
}

/// Serialize `globalThis.__zero_coverage__` to a JSON value if present.
fn serialize_coverage(ctx: &mut Context) -> Option<serde_json::Value> {
    ctx.eval(Source::from_bytes(
        b"JSON.stringify(globalThis.__zero_coverage__ || {})",
    ))
    .ok()
    .and_then(|v| v.as_string().map(|s| s.to_std_string_escaped()))
    .and_then(|s| serde_json::from_str::<serde_json::Value>(&s).ok())
}

/// Recursively walk a describe node, running hooks and `it` bodies.
fn walk_describe(
    node: &JsValue,
    name_chain: &mut Vec<String>,
    outcomes: &mut Vec<TestOutcome>,
    sm: Option<&sourcemap::SourceMap>,
    ctx: &mut Context,
) {
    let obj = match node.as_object() {
        Some(o) => o,
        None => return,
    };

    let before_all_failed = run_before_all(&obj, ctx);
    for child in &js_get_array(&obj, "children", ctx) {
        let Some(child_obj) = child.as_object() else {
            continue;
        };
        let fn_val = child_obj
            .get(boa_engine::js_string!("fn"), ctx)
            .unwrap_or(JsValue::undefined());
        let child_name = js_get_string(child, "name", ctx);
        if fn_val.is_callable() {
            run_it_node(
                node,
                &fn_val,
                child_name,
                name_chain,
                outcomes,
                before_all_failed.as_deref(),
                sm,
                ctx,
            );
        } else {
            name_chain.push(child_name);
            walk_describe(child, name_chain, outcomes, sm, ctx);
            name_chain.pop();
        }
    }

    for hook in &js_get_array(&obj, "afterAll", ctx) {
        let _ = call_and_drain(hook, ctx);
    }
}

/// Run all `beforeAll` hooks on `obj`. Returns `Some(reason)` if any threw —
/// the caller propagates this as a per-test skip reason.
fn run_before_all(obj: &boa_engine::JsObject, ctx: &mut Context) -> Option<String> {
    for hook in &js_get_array(obj, "beforeAll", ctx) {
        if let Err(captured) = call_and_drain(hook, ctx) {
            return Some(format!("beforeAll failed: {}", captured.message));
        }
    }
    None
}

/// Execute a single `it` node: run ancestor `beforeEach` hooks, the test body,
/// then `afterEach` hooks, and push the resulting `TestOutcome`.
#[allow(clippy::too_many_arguments)]
fn run_it_node(
    parent: &JsValue,
    fn_val: &JsValue,
    child_name: String,
    name_chain: &mut Vec<String>,
    outcomes: &mut Vec<TestOutcome>,
    before_all_failed: Option<&str>,
    sm: Option<&sourcemap::SourceMap>,
    ctx: &mut Context,
) {
    name_chain.push(child_name);

    if let Some(reason) = before_all_failed {
        outcomes.push(TestOutcome {
            name_chain: name_chain.clone(),
            status: Status::Skipped(reason.to_string()),
            duration_ms: 0,
            failure: None,
        });
        name_chain.pop();
        return;
    }

    let before_each = collect_hooks(parent, "beforeEach", ctx);
    let after_each = collect_hooks(parent, "afterEach", ctx);

    let mut skip_reason: Option<String> = None;
    for hook in &before_each {
        if let Err(captured) = call_and_drain(hook, ctx) {
            skip_reason = Some(format!("beforeEach failed: {}", captured.message));
            break;
        }
    }

    let start = Instant::now();
    let result = if skip_reason.is_none() {
        call_and_drain(fn_val, ctx)
    } else {
        Ok(())
    };
    let duration_ms = start.elapsed().as_millis();

    let (status, failure) = match (skip_reason, result) {
        (Some(reason), _) => (Status::Skipped(reason), None),
        (None, Ok(())) => (Status::Passed, None),
        (None, Err(captured)) => (Status::Failed, Some(build_failure(captured, sm))),
    };

    outcomes.push(TestOutcome {
        name_chain: name_chain.clone(),
        status,
        duration_ms,
        failure,
    });
    name_chain.pop();

    for hook in &after_each {
        let _ = call_and_drain(hook, ctx);
    }
}

/// Collect `hookName` arrays from the given describe node (does not walk ancestors
/// — ancestor hooks are composed by the walk at call time).
fn collect_hooks(node: &JsValue, hook_name: &str, ctx: &mut Context) -> Vec<JsValue> {
    node.as_object()
        .map(|obj| js_get_array(&obj, hook_name, ctx))
        .unwrap_or_default()
}

/// Call `fn_val` and drain the job queue; return a `CapturedError` on throw.
fn call_and_drain(fn_val: &JsValue, ctx: &mut Context) -> Result<(), CapturedError> {
    let result = match fn_val.as_callable() {
        Some(f) => f.call(&JsValue::undefined(), &[], ctx),
        None => {
            return Err(CapturedError {
                message: "value is not callable".to_string(),
                stack: None,
                user_frame: None,
            });
        }
    };

    match result {
        Err(e) => return Err(capture_from_js_error(&e, ctx)),
        Ok(val) => {
            // If the return value is a Promise, drain until it settles.
            if let Some(obj) = val.as_object()
                && let Ok(promise) = JsPromise::from_object(obj.clone())
            {
                loop {
                    let _ = ctx.run_jobs();
                    match promise.state() {
                        PromiseState::Pending => continue,
                        PromiseState::Fulfilled(_) => break,
                        PromiseState::Rejected(reason) => {
                            return Err(capture_from_js_value(reason, ctx));
                        }
                    }
                }
            }
        }
    }

    Ok(())
}

/// Pull `message`, `.stack`, and `._userFrame` off a JS value (typically an
/// Error object). Always succeeds: missing fields become `None`.
fn capture_from_js_value(val: JsValue, ctx: &mut Context) -> CapturedError {
    let message = val
        .to_string(ctx)
        .map(|s| s.to_std_string_escaped())
        .unwrap_or_else(|_| "<non-string error>".to_string());
    let (stack, user_frame) = match val.as_object() {
        Some(obj) => {
            let stack = obj
                .get(boa_engine::js_string!("stack"), ctx)
                .ok()
                .and_then(|v| v.as_string().map(|s| s.to_std_string_escaped()));
            let user_frame = obj
                .get(boa_engine::js_string!("_userFrame"), ctx)
                .ok()
                .and_then(|v| v.as_string().map(|s| s.to_std_string_escaped()));
            (stack, user_frame)
        }
        None => (None, None),
    };
    CapturedError {
        message,
        stack,
        user_frame,
    }
}

/// Same as [`capture_from_js_value`] but accepts a [`JsError`]. Uses
/// [`JsError::Display`] (which embeds Boa's shadow-stack frames) as the stack
/// source, since user-constructed `Error` objects do not carry a `.stack`
/// property in Boa.
fn capture_from_js_error(e: &JsError, ctx: &mut Context) -> CapturedError {
    let display = e.to_string();
    let (message, stack) = match display.find('\n') {
        Some(idx) => (
            display[..idx].to_string(),
            Some(display[idx + 1..].to_string()),
        ),
        None => (display, None),
    };
    let user_frame = e.as_opaque().and_then(|v| {
        v.as_object().and_then(|obj| {
            obj.get(boa_engine::js_string!("_userFrame"), ctx)
                .ok()
                .and_then(|val| val.as_string().map(|s| s.to_std_string_escaped()))
        })
    });
    CapturedError {
        message,
        stack,
        user_frame,
    }
}

/// Turn a `CapturedError` into a `Failure` with source-mapped message, stack,
/// and location. Prefers the JS-side `_userFrame` over a parsed stack walk.
fn build_failure(captured: CapturedError, sm: Option<&sourcemap::SourceMap>) -> Failure {
    let message = remap_positions(&captured.message, sm);
    let stack = captured.stack.as_deref().map(|s| remap_positions(s, sm));
    let location = compute_location(captured.user_frame.as_deref(), stack.as_deref(), sm);
    Failure {
        message,
        stack,
        location,
    }
}

/// Choose a source location: prefer remapped `user_frame`, otherwise walk the
/// already-remapped stack for the first user-code frame.
///
/// The walk passes over framework-internal paths via [`is_user_path`], then
/// also skips frames whose function name appears in
/// [`FRAMEWORK_REGISTRATION_NAMES`] — those are calls that *contain* the
/// throw (e.g. `it(...)`), not the throw site itself. If no frame survives
/// both filters, the walker falls back to the first non-internal frame so
/// callers never lose a location they would have had under the old logic.
fn compute_location(
    user_frame: Option<&str>,
    remapped_stack: Option<&str>,
    sm: Option<&sourcemap::SourceMap>,
) -> Option<SourceLoc> {
    if let Some(uf) = user_frame {
        let remapped = remap_positions(uf, sm);
        if let Some(loc) = parse_simple_frame(&remapped) {
            return Some(loc);
        }
    }
    let stack_text = remapped_stack?;
    let mut fallback: Option<SourceLoc> = None;
    for line in stack_text.lines() {
        let Some((fn_name, path, l, c)) = parse_stack_frame(line) else {
            continue;
        };
        if !is_user_path(&path) {
            continue;
        }
        let loc = SourceLoc {
            file: PathBuf::from(&path),
            line: l,
            column: c,
        };
        let is_registration = fn_name
            .as_deref()
            .map(|n| FRAMEWORK_REGISTRATION_NAMES.contains(&n))
            .unwrap_or(false);
        if !is_registration {
            return Some(loc);
        }
        if fallback.is_none() {
            fallback = Some(loc);
        }
    }
    fallback
}

/// Parse a `"path:line:col"` string into a [`SourceLoc`].
fn parse_simple_frame(s: &str) -> Option<SourceLoc> {
    let re = regex::Regex::new(r"^(.+):(\d+):(\d+)$").ok()?;
    let caps = re.captures(s)?;
    Some(SourceLoc {
        file: PathBuf::from(&caps[1]),
        line: caps[2].parse().ok()?,
        column: caps[3].parse().ok()?,
    })
}

/// Parse a single stack-trace line into `(fn_name, path, line, column)`.
/// Accepts V8 `"    at fn (path:L:C)"`, SpiderMonkey `"fn@path:L:C"`, and
/// plain `"path:L:C"`. `fn_name` is `None` for plain frames or when the
/// format provides no function name.
fn parse_stack_frame(line: &str) -> Option<(Option<String>, String, u32, u32)> {
    let re = regex::Regex::new(r"(?:\(|@|\s)([^\s()@]+):(\d+):(\d+)\)?\s*$").ok()?;
    let caps = re.captures(line)?;
    let path = caps[1].to_string();
    let l: u32 = caps[2].parse().ok()?;
    let c: u32 = caps[3].parse().ok()?;
    let fn_name = extract_fn_name(line);
    Some((fn_name, path, l, c))
}

/// Pull the function name from a stack frame line.
/// V8 `"    at NAME (path:...)"` → `Some(NAME)`.
/// SpiderMonkey `"NAME@path:..."` → `Some(NAME)`.
/// `"    at path:..."` (no function name) or plain `"path:..."` → `None`.
fn extract_fn_name(line: &str) -> Option<String> {
    let v8 = regex::Regex::new(r"^\s*at\s+([^\s(]+)\s+\(").ok()?;
    if let Some(caps) = v8.captures(line) {
        return Some(caps[1].to_string());
    }
    let sm = regex::Regex::new(r"^([^@\s][^@]*?)@").ok()?;
    if let Some(caps) = sm.captures(line) {
        return Some(caps[1].to_string());
    }
    None
}

/// Returns true if `path` points at user code (not a framework-internal module
/// nor a `node:`-prefixed pseudo-module).
fn is_user_path(path: &str) -> bool {
    if path.starts_with("node:") {
        return false;
    }
    let base = path.rsplit_once('/').map(|(_, b)| b).unwrap_or(path);
    !FRAMEWORK_INTERNAL_BASENAMES.contains(&base)
}

// ---------------------------------------------------------------------------
// JS value helpers
// ---------------------------------------------------------------------------

fn js_get_string(val: &JsValue, key: &str, ctx: &mut Context) -> String {
    val.as_object()
        .and_then(|obj| obj.get(boa_engine::JsString::from(key), ctx).ok())
        .and_then(|v| v.as_string().map(|s| s.to_std_string_escaped()))
        .unwrap_or_default()
}

fn js_get_array(obj: &boa_engine::JsObject, key: &str, ctx: &mut Context) -> Vec<JsValue> {
    let val = obj
        .get(boa_engine::JsString::from(key), ctx)
        .unwrap_or(JsValue::undefined());
    if let Some(arr_obj) = val.as_object()
        && let Ok(arr) = JsArray::from_object(arr_obj.clone())
    {
        let len = arr.length(ctx).unwrap_or(0);
        return (0..len).filter_map(|i| arr.get(i, ctx).ok()).collect();
    }
    vec![]
}

fn js_err_to_failure(e: &JsError, ctx: &mut Context) -> Failure {
    build_failure(capture_from_js_error(e, ctx), None)
}

fn js_val_to_failure(val: JsValue, ctx: &mut Context) -> Failure {
    build_failure(capture_from_js_value(val, ctx), None)
}

/// Install a minimal `console` object on `globalThis`.
fn install_console(ctx: &mut Context) {
    use boa_engine::NativeFunction;
    use boa_engine::object::ObjectInitializer;

    let log = NativeFunction::from_fn_ptr(|_, args, ctx| {
        let parts: Vec<String> = args
            .iter()
            .map(|v| {
                v.to_string(ctx)
                    .map(|s| s.to_std_string_escaped())
                    .unwrap_or_else(|_| "<?>".to_string())
            })
            .collect();
        println!("{}", parts.join(" "));
        Ok(JsValue::undefined())
    });
    let warn = NativeFunction::from_fn_ptr(|_, args, ctx| {
        let parts: Vec<String> = args
            .iter()
            .map(|v| {
                v.to_string(ctx)
                    .map(|s| s.to_std_string_escaped())
                    .unwrap_or_else(|_| "<?>".to_string())
            })
            .collect();
        eprintln!("warn: {}", parts.join(" "));
        Ok(JsValue::undefined())
    });
    let error = NativeFunction::from_fn_ptr(|_, args, ctx| {
        let parts: Vec<String> = args
            .iter()
            .map(|v| {
                v.to_string(ctx)
                    .map(|s| s.to_std_string_escaped())
                    .unwrap_or_else(|_| "<?>".to_string())
            })
            .collect();
        eprintln!("error: {}", parts.join(" "));
        Ok(JsValue::undefined())
    });

    let console = ObjectInitializer::new(ctx)
        .function(log, boa_engine::js_string!("log"), 0)
        .function(warn, boa_engine::js_string!("warn"), 0)
        .function(error, boa_engine::js_string!("error"), 0)
        .build();

    ctx.global_object()
        .set(boa_engine::js_string!("console"), console, false, ctx)
        .expect("failed to install console");
}

/// Install `__readWorkspaceFile__(relPath) -> string` on `globalThis`.
///
/// Framework-internal helper used only by the matcher-drift self-test; it is
/// NOT part of the public `zero/test` surface. Reads are scoped to the
/// workspace root: the joined path is canonicalised and must stay inside the
/// canonicalised root, so `..` escapes and symlink traversal are rejected.
fn install_workspace_file_reader(ctx: &mut Context, root: &Path) {
    use boa_engine::{JsNativeError, NativeFunction};

    let canonical_root = root.canonicalize().unwrap_or_else(|_| root.to_path_buf());

    // SAFETY: the captured `PathBuf` holds no GC-traceable types, so it cannot
    // create a dangling trace pointer — the invariant `from_closure` requires.
    let reader = unsafe {
        NativeFunction::from_closure(move |_, args, _ctx| {
            let rel = args
                .first()
                .and_then(boa_engine::JsValue::as_string)
                .ok_or_else(|| {
                    JsNativeError::typ()
                        .with_message("__readWorkspaceFile__: expected a string path")
                })?
                .to_std_string_escaped();
            let canonical = canonical_root.join(&rel).canonicalize().map_err(|e| {
                JsNativeError::error()
                    .with_message(format!("__readWorkspaceFile__: cannot resolve {rel}: {e}"))
            })?;
            if !canonical.starts_with(&canonical_root) {
                return Err(JsNativeError::error()
                    .with_message(format!(
                        "__readWorkspaceFile__: {rel} escapes workspace root"
                    ))
                    .into());
            }
            let contents = std::fs::read_to_string(&canonical).map_err(|e| {
                JsNativeError::error()
                    .with_message(format!("__readWorkspaceFile__: read failed for {rel}: {e}"))
            })?;
            Ok(JsValue::from(boa_engine::js_string!(contents)))
        })
    };

    ctx.register_global_callable(boa_engine::js_string!("__readWorkspaceFile__"), 1, reader)
        .expect("failed to install __readWorkspaceFile__");
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write as _;
    use tempfile::NamedTempFile;

    thread_local! {
        static FORCE_TEARDOWN_PANIC: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
    }

    /// Read the thread-local teardown-panic flag from inside the harness.
    /// Always `false` in production builds (the module isn't compiled).
    pub(super) fn should_force_teardown_panic() -> bool {
        FORCE_TEARDOWN_PANIC.with(|cell| cell.get())
    }

    struct ForceTeardownPanicGuard;

    impl ForceTeardownPanicGuard {
        fn install() -> Self {
            FORCE_TEARDOWN_PANIC.with(|cell| cell.set(true));
            Self
        }
    }

    impl Drop for ForceTeardownPanicGuard {
        fn drop(&mut self) {
            FORCE_TEARDOWN_PANIC.with(|cell| cell.set(false));
        }
    }

    fn write_temp_js(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::with_suffix(".js").unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    fn write_temp_ts(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::with_suffix(".test.ts").unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    #[test]
    fn run_file_handles_ts_entry() {
        let f = write_temp_ts(
            r#"import { describe, it, expect } from "zero/test";
const n: number = 1;
describe("g", () => { it("ok", () => expect(n).toBe(1)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn passing_test_produces_passed_outcome() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => { it("ok", () => expect(1).toBe(1)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].name_chain, vec!["g", "ok"]);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn run_file_with_coverage_returns_coverage_snapshot() {
        use crate::coverage::CoverageScope;
        use crate::loader::CoverageContext;

        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("src")).unwrap();
        std::fs::write(
            root.join("src").join("foo.ts"),
            "export function bar(){ return 42 }\n",
        )
        .unwrap();
        let test_path = root.join("foo.test.ts");
        std::fs::write(
            &test_path,
            r#"import { describe, it, expect } from "zero/test";
import { bar } from "./src/foo.ts";
describe("g", () => { it("works", () => expect(bar()).toBe(42)); });
"#,
        )
        .unwrap();

        let scope = CoverageScope::new(root.to_path_buf(), root.join("dist"));
        let ctx = Rc::new(CoverageContext::new(scope));
        let outcome = run_file_with_coverage(root, &test_path, Some(ctx.clone()));
        assert!(
            outcome.result.load_error.is_none(),
            "load_error: {:?}",
            outcome.result.load_error
        );
        assert_eq!(outcome.result.outcomes.len(), 1);
        let cov = outcome.coverage.expect("coverage snapshot present");
        let maps = ctx.drain_maps();
        assert!(!maps.is_empty(), "expected at least one instrumented file");
        // The snapshot should include the foo.ts file with bar fn hit.
        let foo_key = maps[0].file.to_string_lossy().to_string();
        let bar_hits = cov
            .get(&foo_key)
            .and_then(|v| v.get("fns"))
            .and_then(|v| v.get("bar"))
            .and_then(|v| v.as_u64())
            .unwrap_or(0);
        assert_eq!(bar_hits, 1, "expected fns.bar=1, snapshot: {cov}");
    }

    #[test]
    fn failing_assertion_carries_location() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => { it("fail", () => expect(1).toBe(2)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        let failure = result.outcomes[0]
            .failure
            .as_ref()
            .expect("failure present");
        let loc = failure.location.as_ref().expect("location should be Some");
        let expected_file = f.path();
        assert_eq!(
            loc.file, expected_file,
            "loc.file did not match temp test path; stack: {:?}",
            failure.stack
        );
        assert!(loc.line >= 1);
        assert!(loc.column >= 1);
    }

    #[test]
    fn load_error_top_level_throw_degrades_gracefully_to_no_location() {
        // Boa 0.21 does not expose `Error.stack` to JS, and module-evaluation
        // promise rejections discard the engine's internal shadow-stack — so a
        // top-level `throw new Error(...)` cannot recover a call-site frame.
        // Per spec §1.1, when no user frame can be identified `location` is
        // None and the reporter falls back to the message-only path. This test
        // pins that contract.
        let f = write_temp_js(
            r#"import { describe } from "zero/test";
function boom() { throw new Error("nope at top"); }
boom();
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        let le = result.load_error.expect("expected load_error");
        assert!(
            le.message.contains("nope at top"),
            "message should preserve user-thrown text: {:?}",
            le.message
        );
        // location is allowed to be None here; verifying that no panic / error
        // is reached and the path still surfaces the message is enough.
        let _ = le.location;
    }

    #[test]
    fn location_skips_runtime_frames() {
        // The matcher frames (zero/test internal) are in the stack between the
        // throw site and the user call; the picked location must point at the
        // user file, not at the matcher.
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
function callsite() { expect(1).toBe(2); }
describe("g", () => { it("fail", () => callsite()); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        let failure = result.outcomes[0].failure.as_ref().expect("failure");
        let loc = failure.location.as_ref().expect("location");
        assert_eq!(loc.file, f.path());
        // `callsite` body is on line 2 — assert at least we point at the user file
        // and a plausible line (1..=3 covers any minor numbering variance).
        assert!(
            (1..=3).contains(&loc.line),
            "loc.line should be inside the user file's first few lines, got {} (stack: {:?})",
            loc.line,
            failure.stack
        );
    }

    #[test]
    fn failing_assertion_produces_failed_outcome() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => { it("fail", () => expect(1).toBe(2)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Failed);
        let msg = result.outcomes[0].failure.as_ref().unwrap().message.clone();
        assert!(msg.contains('1') && msg.contains('2'), "message: {msg}");
    }

    #[test]
    fn top_level_throw_sets_load_error() {
        let f = write_temp_js(
            r#"import { describe } from "zero/test";
throw new Error("nope");
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_some(), "expected load_error");
        assert!(result.outcomes.is_empty());
    }

    #[test]
    fn failing_before_each_skips_subsequent_its() {
        let f = write_temp_js(
            r#"import { describe, it, beforeEach, expect } from "zero/test";
describe("g", () => {
  beforeEach(() => { throw new Error("oh no"); });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            assert!(
                matches!(o.status, Status::Skipped(_)),
                "expected Skipped, got {:?} for {}",
                o.status,
                o.name_chain.join(" > ")
            );
        }
    }

    #[test]
    fn document_root_props_are_writable_for_isolation() {
        // Regression: `document.documentElement` / `head` / `body` were
        // getter-only, so a `beforeEach` that swaps them for isolation threw
        // "cannot set non-writable property" and the test was silently
        // reported as Skipped. They now have setters, so the swap succeeds and
        // the test runs to a real Pass/Fail. Mirrors the demo's Layout.test.ts
        // theme-isolation pattern (swap the root, assert a setAttribute write,
        // restore in afterEach).
        let f = write_temp_js(
            r#"import { describe, it, beforeEach, afterEach, expect } from "zero/test";
function fakeRoot() {
  const attrs = new Map();
  return {
    setAttribute: (k, v) => void attrs.set(k, v),
    getAttribute: (k) => (attrs.has(k) ? attrs.get(k) : null),
  };
}
describe("root isolation", () => {
  let savedEl, savedHead, savedBody;
  beforeEach(() => {
    savedEl = document.documentElement;
    savedHead = document.head;
    savedBody = document.body;
    document.documentElement = fakeRoot();
    document.head = fakeRoot();
    document.body = fakeRoot();
  });
  afterEach(() => {
    document.documentElement = savedEl;
    document.head = savedHead;
    document.body = savedBody;
  });
  it("captures writes on the swapped root", () => {
    document.documentElement.setAttribute("data-theme", "dark");
    expect(document.documentElement.getAttribute("data-theme")).toBe("dark");
  });
  it("swaps head and body too", () => {
    document.head.setAttribute("x", "1");
    document.body.setAttribute("y", "2");
    expect(document.head.getAttribute("x")).toBe("1");
    expect(document.body.getAttribute("y")).toBe("2");
  });
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none(), "unexpected load error");
        for o in &result.outcomes {
            assert!(
                matches!(o.status, Status::Passed),
                "expected Passed, got {:?} for {}",
                o.status,
                o.name_chain.join(" > ")
            );
        }
        assert_eq!(result.outcomes.len(), 2, "expected both its to run");
    }

    #[test]
    fn parse_simple_frame_extracts_components() {
        let loc = super::parse_simple_frame("/path/to/a.js:12:34").unwrap();
        assert_eq!(loc.file, PathBuf::from("/path/to/a.js"));
        assert_eq!(loc.line, 12);
        assert_eq!(loc.column, 34);
    }

    #[test]
    fn parse_simple_frame_returns_none_when_missing_position() {
        assert!(super::parse_simple_frame("/path/no/position.js").is_none());
    }

    #[test]
    fn parse_stack_frame_accepts_v8_format() {
        let got = super::parse_stack_frame("    at fn (/x/a.js:1:2)").unwrap();
        assert_eq!(got, (Some("fn".to_string()), "/x/a.js".to_string(), 1, 2));
    }

    #[test]
    fn parse_stack_frame_accepts_spidermonkey_format() {
        let got = super::parse_stack_frame("fn@/x/a.js:3:4").unwrap();
        assert_eq!(got, (Some("fn".to_string()), "/x/a.js".to_string(), 3, 4));
    }

    #[test]
    fn parse_stack_frame_returns_none_on_garbage() {
        assert!(super::parse_stack_frame("definitely not a frame").is_none());
    }

    #[test]
    fn parse_stack_frame_v8_no_function_name() {
        // V8 "    at path:L:C" frames have no function name.
        let got = super::parse_stack_frame("    at /x/a.js:5:6").unwrap();
        assert_eq!(got, (None, "/x/a.js".to_string(), 5, 6));
    }

    #[test]
    fn parse_stack_frame_extracts_registration_name() {
        let got = super::parse_stack_frame("    at it (/x/test.js:42:7)").unwrap();
        assert_eq!(
            got,
            (Some("it".to_string()), "/x/test.js".to_string(), 42, 7)
        );
    }

    #[test]
    fn is_user_path_rejects_node_prefix() {
        assert!(!super::is_user_path("node:internal/process/task_queues"));
    }

    #[test]
    fn is_user_path_rejects_framework_internal_basenames() {
        assert!(!super::is_user_path("/foo/test.js"));
        assert!(!super::is_user_path("/foo/template.js"));
        assert!(!super::is_user_path("/foo/reactivity.js"));
        assert!(!super::is_user_path("/foo/app.js"));
        assert!(!super::is_user_path("/foo/router.js"));
        assert!(!super::is_user_path("/foo/dom-shim.js"));
        assert!(!super::is_user_path("/foo/http.js"));
    }

    #[test]
    fn is_user_path_accepts_user_modules() {
        assert!(super::is_user_path("/x/src/app.test.js"));
        assert!(super::is_user_path("/x/src/home.ts"));
        assert!(super::is_user_path("just_a_bare_name.js"));
    }

    #[test]
    fn compute_location_prefers_user_frame_over_stack() {
        let user = Some("/x/src/a.ts:1:2");
        let stack = Some("at thing (/x/src/other.ts:5:6)");
        let loc = super::compute_location(user, stack, None).unwrap();
        assert_eq!(loc.file, PathBuf::from("/x/src/a.ts"));
        assert_eq!(loc.line, 1);
    }

    #[test]
    fn compute_location_walks_stack_when_no_user_frame() {
        // First framework frame is skipped, second user frame is picked.
        let stack = Some("at h (/x/src/template.js:1:2)\nat g (/x/src/user.ts:3:4)");
        let loc = super::compute_location(None, stack, None).unwrap();
        assert_eq!(loc.file, PathBuf::from("/x/src/user.ts"));
        assert_eq!(loc.line, 3);
        assert_eq!(loc.column, 4);
    }

    #[test]
    fn compute_location_returns_none_when_no_user_frame_anywhere() {
        let stack = Some("at h (/x/src/template.js:1:2)\nat g (/x/src/app.js:3:4)");
        assert!(super::compute_location(None, stack, None).is_none());
    }

    #[test]
    fn compute_location_returns_none_when_no_input() {
        assert!(super::compute_location(None, None, None).is_none());
    }

    #[test]
    fn compute_location_skips_user_it_registration_frame() {
        // The `it()` registration frame is in user code (test.test.js) but
        // it's not the throw site — the throw happens inside the body that
        // `it` wraps. Walker should skip past `it` and pick the next frame.
        let stack = Some(
            "at it (/x/src/a.test.ts:10:5)\n\
             at body (/x/src/a.test.ts:3:11)",
        );
        let loc = super::compute_location(None, stack, None).unwrap();
        assert_eq!(loc.line, 3);
        assert_eq!(loc.column, 11);
    }

    #[test]
    fn compute_location_falls_back_to_registration_when_no_other_frame() {
        // No other user frames; the registration frame is all we have.
        // Don't return None — better wrong than empty.
        let stack = Some("at it (/x/src/a.test.ts:10:5)");
        let loc = super::compute_location(None, stack, None).unwrap();
        assert_eq!(loc.line, 10);
    }

    #[test]
    fn compute_location_skips_describe_render_cleanup_frames() {
        for fn_name in ["describe", "render", "cleanup", "beforeEach"] {
            let stack_str = format!(
                "at {fn_name} (/x/src/a.test.ts:10:5)\n\
                 at body (/x/src/a.test.ts:7:9)",
            );
            let loc = super::compute_location(None, Some(&stack_str), None).unwrap();
            assert_eq!(loc.line, 7, "{fn_name} should be skipped");
        }
    }

    #[test]
    fn remap_positions_passthrough_without_sourcemap() {
        let s = "at f (/x/a.ts:5:7)";
        assert_eq!(super::remap_positions(s, None), s);
    }

    #[test]
    fn nested_describe_blocks_walk_in_order() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("outer", () => {
  it("o-a", () => expect(1).toBe(1));
  describe("inner", () => {
    it("i-a", () => expect(2).toBe(2));
    it("i-b", () => expect(3).toBe(3));
  });
  it("o-b", () => expect(4).toBe(4));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        let names: Vec<_> = result
            .outcomes
            .iter()
            .map(|o| o.name_chain.join(" > "))
            .collect();
        assert!(names.contains(&"outer > o-a".to_string()), "{names:?}");
        assert!(
            names.contains(&"outer > inner > i-a".to_string()),
            "{names:?}"
        );
        assert!(
            names.contains(&"outer > inner > i-b".to_string()),
            "{names:?}"
        );
        assert!(names.contains(&"outer > o-b".to_string()), "{names:?}");
    }

    #[test]
    fn before_all_failure_skips_all_its_with_reason() {
        let f = write_temp_js(
            r#"import { describe, it, beforeAll, expect } from "zero/test";
describe("g", () => {
  beforeAll(() => { throw new Error("boot failure"); });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            match &o.status {
                Status::Skipped(reason) => assert!(reason.contains("beforeAll")),
                other => panic!("expected Skipped, got {other:?}"),
            }
        }
    }

    #[test]
    fn after_each_runs_even_after_test_failure() {
        let f = write_temp_js(
            r#"import { describe, it, afterEach, expect } from "zero/test";
let tail = [];
describe("g", () => {
  afterEach(() => { tail.push("ae"); });
  it("fail", () => expect(1).toBe(2));
  it("pass", () => { expect(tail.length).toBe(1); });
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        let pass = result
            .outcomes
            .iter()
            .find(|o| o.name_chain.iter().any(|n| n == "pass"))
            .unwrap();
        assert!(matches!(pass.status, Status::Passed));
    }

    #[test]
    fn top_level_it_without_describe_runs() {
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("lone", () => expect(1).toBe(1));
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].name_chain, vec!["lone".to_string()]);
        assert!(matches!(result.outcomes[0].status, Status::Passed));
    }

    #[test]
    fn async_test_awaits_promise_resolution() {
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("awaits", async () => {
  await Promise.resolve();
  expect(2 + 2).toBe(4);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert!(matches!(result.outcomes[0].status, Status::Passed));
    }

    #[test]
    fn async_test_rejection_is_a_failure() {
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("rejects", async () => { throw new Error("rejected"); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert!(matches!(result.outcomes[0].status, Status::Failed));
    }

    #[test]
    fn after_all_runs_after_all_its() {
        let f = write_temp_js(
            r#"import { describe, it, afterAll, expect } from "zero/test";
globalThis.afterAllCount = 0;
describe("g", () => {
  afterAll(() => { globalThis.afterAllCount++; });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            assert!(matches!(o.status, Status::Passed));
        }
    }

    #[test]
    fn console_log_in_test_does_not_crash() {
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("logs", () => {
  console.log("hello");
  console.warn("warn");
  console.error("err");
  expect(1).toBe(1);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert!(matches!(result.outcomes[0].status, Status::Passed));
    }

    #[test]
    fn throwing_non_error_value_still_produces_failed_outcome() {
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("throws-string", () => { throw "literal string"; });
it("throws-number", () => { throw 42; });
it("throws-object", () => { throw { code: "X" }; });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            assert!(matches!(o.status, Status::Failed));
        }
    }

    #[test]
    fn multiple_files_independent_test_state() {
        let f1 = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("alpha", () => expect(1).toBe(1));
"#,
        );
        let f2 = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("beta", () => expect(2).toBe(2));
"#,
        );
        let r1 = run_file(f1.path().parent().unwrap(), f1.path());
        let r2 = run_file(f2.path().parent().unwrap(), f2.path());
        assert_eq!(r1.outcomes.len(), 1);
        assert_eq!(r1.outcomes[0].name_chain, vec!["alpha".to_string()]);
        assert_eq!(r2.outcomes.len(), 1);
        assert_eq!(r2.outcomes[0].name_chain, vec!["beta".to_string()]);
    }

    #[test]
    fn raw_typeerror_reports_throw_line_not_it_line() {
        // A test body that throws a raw TypeError (no matcher _userFrame
        // decoration). The harness should attribute the failure to the
        // throw site, not to the `it(...)` registration line.
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("raw throw", () => {
  const obj = null;
  obj.foo;
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        let failure = result.outcomes[0]
            .failure
            .as_ref()
            .expect("expected failure");
        if let Some(loc) = failure.location.as_ref() {
            // `it(...)` is on line 2; the throw site is on line 4.
            // The registration filter should keep us off line 2.
            assert_ne!(
                loc.line, 2,
                "location should not point at the it() registration line; stack: {:?}",
                failure.stack
            );
        }
    }

    #[test]
    fn explicit_throw_in_test_body_reports_throw_line() {
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("explicit throw", () => {
  throw new Error("boom");
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        let failure = result.outcomes[0]
            .failure
            .as_ref()
            .expect("expected failure");
        assert!(failure.message.contains("boom"));
        if let Some(loc) = failure.location.as_ref() {
            assert_ne!(
                loc.line, 2,
                "location should not point at the it() registration line; stack: {:?}",
                failure.stack
            );
        }
    }

    #[test]
    fn matcher_failure_still_points_at_matcher_call() {
        // Regression: matcher failures already had a useful location.
        // The new registration filter must not regress this path.
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("matcher fail", () => {
  expect(1).toBe(2);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        let failure = result.outcomes[0].failure.as_ref().expect("failure");
        let loc = failure.location.as_ref().expect("location");
        // The matcher call is on line 3.
        assert_eq!(
            loc.line, 3,
            "matcher location should point at the expect() call; stack: {:?}",
            failure.stack
        );
    }

    #[test]
    fn forced_teardown_panic_becomes_structured_failure() {
        // Drive the test-only thread-local trigger to exercise the
        // catch_unwind path: the harness must convert the panic into a
        // synthetic Failed outcome rather than crashing the test process.
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("ok", () => expect(1).toBe(1));
"#,
        );
        let root = f.path().parent().unwrap();
        let _guard = ForceTeardownPanicGuard::install();
        let result = run_file(root, f.path());
        drop(_guard);
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1, "expected one synthetic outcome");
        let outcome = &result.outcomes[0];
        assert!(matches!(outcome.status, Status::Failed));
        let failure = outcome.failure.as_ref().expect("expected failure");
        assert!(
            failure.message.contains("Boa GC panic"),
            "message should mention Boa GC panic, got: {}",
            failure.message
        );
        assert!(
            outcome.name_chain.iter().any(|n| n.contains("teardown")),
            "name should mention teardown: {:?}",
            outcome.name_chain
        );
    }

    #[test]
    fn after_each_failure_does_not_break_subsequent_its() {
        let f = write_temp_js(
            r#"import { describe, it, afterEach, expect } from "zero/test";
describe("g", () => {
  afterEach(() => { throw new Error("cleanup blew up"); });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 2);
        // Both 'a' and 'b' should still have been recorded.
        for o in &result.outcomes {
            assert!(matches!(o.status, Status::Passed));
        }
    }

    #[test]
    fn read_workspace_file_returns_contents() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("known-file.txt"), "hello-from-workspace").unwrap();
        let test_path = root.join("read.test.js");
        std::fs::write(
            &test_path,
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => {
  it("reads workspace file", () => {
    const s = globalThis.__readWorkspaceFile__("known-file.txt");
    expect(s).toContain("hello-from-workspace");
  });
});
"#,
        )
        .unwrap();
        let result = run_file(root, &test_path);
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn read_workspace_file_rejects_escaping_path() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let test_path = root.join("escape.test.js");
        std::fs::write(
            &test_path,
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => {
  it("rejects escape", () => {
    expect(() => globalThis.__readWorkspaceFile__("../outside")).toThrow();
  });
});
"#,
        )
        .unwrap();
        let result = run_file(root, &test_path);
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }
}
