//! QuickJS (rquickjs) harness: boots a fresh runtime/context per file and walks
//! the test tree, producing `FileResult`/`RunOutcome`.

use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::time::Instant;

use rquickjs::convert::Coerced;
use rquickjs::promise::{MaybePromise, PromiseState};
use rquickjs::{Array, Context, Ctx, Error, Function, Module, Object, Runtime, Value};

use zero_runtime::ZERO_DOM_SHIM_BODY;
use zero_transpile::{TranspileOptions, transpile_typescript};

use crate::loader::{CoverageContext, ZeroLoader, ZeroModuleLoader, ZeroResolver};
use crate::result::{Failure, FileResult, SourceLoc, Status, TestOutcome};
use crate::timing::{self, Phase};

/// Combined return from [`run_file_with_coverage`]: the file's outcomes plus
/// (when coverage is enabled) a JSON snapshot of `globalThis.__zero_coverage__`,
/// and the canonical paths the loader resolved during this run.
pub struct RunOutcome {
    pub result: FileResult,
    pub coverage: Option<serde_json::Value>,
    /// Sorted, deduped list of every canonical path the loader resolved while
    /// evaluating this file. Used by `zero mutate` to build a per-test-file
    /// import set for test-impact analysis.
    pub loaded: Vec<PathBuf>,
}

/// Framework-internal runtime module basenames; frames whose path basename is
/// in this set are skipped when picking the topmost user frame from a stack.
const FRAMEWORK_INTERNAL_BASENAMES: &[&str] = &[
    "test.js",
    "template.js",
    "reactivity.js",
    "app.js",
    "router.js",
    "dom-shim.js",
    "http.js",
];

/// Function names that identify test-framework registration call sites.
/// A frame whose function name is one of these is never the actual throw
/// site — it's the call that *contains* the throw. The stack walker skips
/// these when picking the topmost user frame, so a raw `TypeError` (or any
/// non-matcher throw) doesn't get pinned to the `it(...)` registration line.
const FRAMEWORK_REGISTRATION_NAMES: &[&str] = &[
    "it",
    "describe",
    "beforeEach",
    "afterEach",
    "beforeAll",
    "afterAll",
    "cleanup",
    "render",
];

/// A thrown JS error captured from the engine, with stack and user-frame
/// metadata.
pub(crate) struct CapturedError {
    pub(crate) message: String,
    pub(crate) stack: Option<String>,
    pub(crate) user_frame: Option<String>,
}

/// Remap `file.ts:LINE:COL` positions in an engine error string back to their
/// original TypeScript source positions using a source map generated by SWC.
///
/// Without source maps, the engine reports positions in the transpiled JS while
/// attributing them to the original `.ts` filename — producing misleading line
/// numbers. This corrects them so stack-frame lines point at the actual
/// TypeScript source.
pub(crate) fn remap_positions(error: &str, sm: Option<&sourcemap::SourceMap>) -> String {
    let sm = match sm {
        Some(s) => s,
        None => return error.to_string(),
    };
    // Match absolute paths ending in .ts followed by :LINE:COL
    let re = regex::Regex::new(r"([^\s()]+\.ts):(\d+):(\d+)").expect("valid regex");
    re.replace_all(error, |caps: &regex::Captures| {
        let path = &caps[1];
        let line: u32 = caps[2].parse().unwrap_or(1);
        let col: u32 = caps[3].parse().unwrap_or(1);
        // sourcemap crate uses 0-based line/col; the engine reports 1-based
        match sm.lookup_token(line.saturating_sub(1), col.saturating_sub(1)) {
            Some(tok) => {
                let orig_line = tok.get_src_line() + 1;
                let orig_col = tok.get_src_col() + 1;
                format!("{path}:{orig_line}:{orig_col}")
            }
            None => format!("{path}:{line}:{col}"),
        }
    })
    .into_owned()
}

/// Run all tests in `file_abs` and return the collected outcomes.
///
/// # Parameters
/// - `project_root`: absolute path to the project root (used for module resolution).
/// - `file_abs`: absolute path to the test file to run.
///
/// # Returns
/// A [`FileResult`] with all outcomes and any load error.
pub fn run_file(project_root: &Path, file_abs: &Path) -> FileResult {
    run_file_with_coverage(project_root, file_abs, None).result
}

/// Run `file_abs` with a pre-built loader. Used by `zero mutate` to inject a
/// per-mutant overlay of mutated source.
pub fn run_file_with_loader(
    project_root: &Path,
    file_abs: &Path,
    loader: Rc<ZeroModuleLoader>,
) -> FileResult {
    run_with_loader(project_root, file_abs, loader, false).result
}

/// Like [`run_file`] but optionally enables coverage instrumentation. When
/// `coverage` is `Some`, the loader instruments in-scope source files; after
/// the test loop, `globalThis.__zero_coverage__` is serialized to JSON and
/// returned alongside the result.
pub fn run_file_with_coverage(
    project_root: &Path,
    file_abs: &Path,
    coverage: Option<Rc<CoverageContext>>,
) -> RunOutcome {
    let want_coverage = coverage.is_some();
    let loader = match coverage {
        Some(ctx) => Rc::new(ZeroModuleLoader::new_with_coverage(project_root, ctx)),
        None => Rc::new(ZeroModuleLoader::new(project_root)),
    };
    run_with_loader(project_root, file_abs, loader, want_coverage)
}

fn run_with_loader(
    project_root: &Path,
    file_abs: &Path,
    loader: Rc<ZeroModuleLoader>,
    want_coverage: bool,
) -> RunOutcome {
    let rel_path = file_abs
        .strip_prefix(project_root)
        .unwrap_or(file_abs)
        .to_path_buf();
    let rel_for_panic = rel_path.clone();
    let project_root_owned = project_root.to_path_buf();
    let file_abs_owned = file_abs.to_path_buf();

    // Swap in a silent panic hook for the duration of catch_unwind so a
    // teardown panic doesn't dump a stderr trace before the synthetic failure
    // is reported. The guard restores the original hook on drop, even if the
    // closure itself panics.
    let _hook_guard = SilentPanicHookGuard::install();

    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        run_with_loader_inner(
            &project_root_owned,
            &file_abs_owned,
            loader,
            want_coverage,
            rel_path,
        )
    }));
    drop(_hook_guard);

    match result {
        Ok(outcome) => outcome,
        Err(payload) => synthesize_panic_outcome(rel_for_panic, payload),
    }
}

fn run_with_loader_inner(
    project_root: &Path,
    file_abs: &Path,
    loader: Rc<ZeroModuleLoader>,
    want_coverage: bool,
    rel_path: PathBuf,
) -> RunOutcome {
    let raw = match read_test_source(file_abs) {
        Ok(s) => s,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    let (src, ts_source_map) = match prepare_source(raw, file_abs) {
        Ok(out) => out,
        Err(f) => return load_error_outcome(rel_path, f),
    };
    loader.register_path(
        &file_abs.to_string_lossy(),
        file_abs.parent().unwrap_or(project_root),
    );

    let ctx_start = timing::start();
    let rt = match Runtime::new() {
        Ok(r) => r,
        Err(e) => return load_error_outcome(rel_path, infra_failure(format!("runtime: {e}"))),
    };
    rt.set_loader(
        ZeroResolver::new(loader.clone()),
        ZeroLoader::new(loader.clone()),
    );
    let context = match Context::full(&rt) {
        Ok(c) => c,
        Err(e) => return load_error_outcome(rel_path, infra_failure(format!("context: {e}"))),
    };

    let project_root = project_root.to_path_buf();
    let entry_name = file_abs.to_string_lossy().into_owned();

    let inner = context.with(
        |ctx| -> Result<(Vec<TestOutcome>, Option<serde_json::Value>), Failure> {
            install_host(&ctx, &project_root)?;
            timing::record_since(Phase::ContextBuild, ctx_start);

            let shim_start = timing::start();
            eval_dom_shim(&ctx)?;
            timing::record_since(Phase::DomShim, shim_start);

            let eval_start = timing::start();
            evaluate_entry(&ctx, &entry_name, &src)?;
            timing::record_since(Phase::RuntimeEval, eval_start);

            let root = read_test_tree(&ctx)?;
            let mut outcomes = Vec::new();
            let exec_start = timing::start();
            walk_describe(
                &ctx,
                &root,
                &mut Vec::new(),
                &mut outcomes,
                ts_source_map.as_ref(),
            );
            timing::record_since(Phase::TestExec, exec_start);

            let coverage = if want_coverage {
                serialize_coverage(&ctx)
            } else {
                None
            };
            Ok((outcomes, coverage))
        },
    );

    // Test-only injection point for the catch_unwind safety net: force a panic
    // after outcomes are collected but before teardown, to prove the net
    // converts a teardown panic into a structured failure.
    #[cfg(test)]
    if tests::should_force_teardown_panic() {
        panic!("forced teardown panic for test");
    }

    let loaded = loader.loaded_paths();
    match inner {
        Ok((outcomes, coverage)) => RunOutcome {
            result: FileResult {
                path: rel_path,
                outcomes,
                load_error: None,
            },
            coverage,
            loaded,
        },
        Err(f) => load_error_outcome(rel_path, f),
    }
}

type SilentHookState = std::sync::Mutex<(
    usize,
    Option<Box<dyn Fn(&std::panic::PanicHookInfo) + Sync + Send>>,
)>;

fn silent_hook_state() -> &'static SilentHookState {
    static STATE: std::sync::OnceLock<SilentHookState> = std::sync::OnceLock::new();
    STATE.get_or_init(|| std::sync::Mutex::new((0, None)))
}

/// RAII guard: replaces the panic hook with a no-op for the duration of
/// `catch_unwind` so the default stderr backtrace doesn't fire before the
/// synthetic failure is reported. Reference-counted via a process-global
/// mutex so concurrent guards (e.g. parallel `cargo test`) do not stomp on
/// each other's saved hook.
pub(crate) struct SilentPanicHookGuard;

impl SilentPanicHookGuard {
    pub(crate) fn install() -> Self {
        let mut guard = silent_hook_state()
            .lock()
            .expect("panic hook mutex poisoned");
        if guard.0 == 0 {
            let prev = std::panic::take_hook();
            std::panic::set_hook(Box::new(|_| {}));
            guard.1 = Some(prev);
        }
        guard.0 += 1;
        Self
    }
}

impl Drop for SilentPanicHookGuard {
    fn drop(&mut self) {
        let mut guard = silent_hook_state()
            .lock()
            .expect("panic hook mutex poisoned");
        if guard.0 == 0 {
            return;
        }
        guard.0 -= 1;
        if guard.0 == 0
            && let Some(prev) = guard.1.take()
        {
            std::panic::set_hook(prev);
        }
    }
}

/// Synthesize a structured `RunOutcome` for a panic caught from
/// [`run_with_loader_inner`]. Outcomes collected before the panic are lost
/// because the inner stack unwound — this is the accepted trade-off; a teardown
/// panic is rare, and the synthetic failure makes the run loud instead of
/// crashing the process.
pub(crate) fn synthesize_panic_outcome(
    rel_path: PathBuf,
    payload: Box<dyn std::any::Any + Send>,
) -> RunOutcome {
    let msg = panic_payload_to_string(payload.as_ref());
    RunOutcome {
        result: FileResult {
            path: rel_path,
            outcomes: vec![TestOutcome {
                name_chain: vec!["<panic during teardown>".to_string()],
                status: Status::Failed,
                duration_ms: 0,
                failure: Some(Failure {
                    message: format!("panic during teardown: {msg}"),
                    stack: None,
                    location: None,
                }),
            }],
            load_error: None,
        },
        coverage: None,
        loaded: vec![],
    }
}

fn panic_payload_to_string(p: &(dyn std::any::Any + Send)) -> String {
    if let Some(s) = p.downcast_ref::<&'static str>() {
        return (*s).to_string();
    }
    if let Some(s) = p.downcast_ref::<String>() {
        return s.clone();
    }
    "<non-string panic payload>".to_string()
}

/// Wrap a load-time `Failure` into an empty `RunOutcome` keyed by `rel_path`.
pub(crate) fn load_error_outcome(rel_path: PathBuf, failure: Failure) -> RunOutcome {
    RunOutcome {
        result: FileResult {
            path: rel_path,
            outcomes: vec![],
            load_error: Some(failure),
        },
        coverage: None,
        loaded: vec![],
    }
}

/// Build a `Failure` for an infrastructure error (no JS stack).
fn infra_failure(message: String) -> Failure {
    Failure {
        message,
        stack: None,
        location: None,
    }
}

/// Install `console` (via native `__print`/`__eprint`) and a sandboxed
/// `__readWorkspaceFile__` on `globalThis`.
fn install_host<'js>(ctx: &Ctx<'js>, root: &Path) -> Result<(), Failure> {
    let g = ctx.globals();
    g.set(
        "__print",
        Function::new(ctx.clone(), |s: String| println!("{s}"))
            .map_err(|e| infra_failure(format!("__print: {e}")))?,
    )
    .map_err(|e| infra_failure(format!("install __print: {e}")))?;
    g.set(
        "__eprint",
        Function::new(ctx.clone(), |s: String| eprintln!("{s}"))
            .map_err(|e| infra_failure(format!("__eprint: {e}")))?,
    )
    .map_err(|e| infra_failure(format!("install __eprint: {e}")))?;
    ctx.eval::<(), _>(
        r#"globalThis.console = {
            log:   function(){ __print(Array.prototype.join.call(arguments,' ')); },
            warn:  function(){ __eprint('warn: '+Array.prototype.join.call(arguments,' ')); },
            error: function(){ __eprint('error: '+Array.prototype.join.call(arguments,' ')); },
            debug: function(){},
            info:  function(){ __print(Array.prototype.join.call(arguments,' ')); },
        };"#,
    )
    .map_err(|e| infra_failure(format!("console install: {e}")))?;

    let canonical_root = root.canonicalize().unwrap_or_else(|_| root.to_path_buf());
    let reader = Function::new(
        ctx.clone(),
        move |rel: String| -> rquickjs::Result<String> {
            let canonical = canonical_root.join(&rel).canonicalize().map_err(|e| {
                Error::new_loading(format!("__readWorkspaceFile__: cannot resolve {rel}: {e}"))
            })?;
            if !canonical.starts_with(&canonical_root) {
                return Err(Error::new_loading(format!(
                    "__readWorkspaceFile__: {rel} escapes workspace root"
                )));
            }
            std::fs::read_to_string(&canonical).map_err(|e| {
                Error::new_loading(format!("__readWorkspaceFile__: read failed for {rel}: {e}"))
            })
        },
    )
    .map_err(|e| infra_failure(format!("__readWorkspaceFile__: {e}")))?;
    g.set("__readWorkspaceFile__", reader)
        .map_err(|e| infra_failure(format!("install __readWorkspaceFile__: {e}")))?;
    Ok(())
}

/// Evaluate the framework DOM shim as a global script so `globalThis.document`
/// and friends exist before user modules run.
fn eval_dom_shim(ctx: &Ctx<'_>) -> Result<(), Failure> {
    ctx.eval::<(), _>(ZERO_DOM_SHIM_BODY).map_err(|e| match e {
        Error::Exception => build_failure(capture_thrown(ctx), None),
        other => infra_failure(format!("dom-shim eval error: {other}")),
    })
}

/// Read the on-disk test source.
pub(crate) fn read_test_source(file_abs: &Path) -> Result<String, Failure> {
    std::fs::read_to_string(file_abs).map_err(|e| Failure {
        message: format!("cannot read {}: {e}", file_abs.display()),
        stack: None,
        location: None,
    })
}

/// For `.ts` files transpile to JS and return a source map; for `.js` files
/// pass through unchanged.
pub(crate) fn prepare_source(
    raw: String,
    file_abs: &Path,
) -> Result<(String, Option<sourcemap::SourceMap>), Failure> {
    if file_abs.extension().and_then(|e| e.to_str()) != Some("ts") {
        return Ok((raw, None));
    }
    let logical = file_abs.to_string_lossy().into_owned();
    let t_start = timing::start();
    let out = transpile_typescript(
        &raw,
        &TranspileOptions {
            filename: &logical,
            inline_source_map: false,
            emit_source_map: true,
        },
    )
    .map_err(|e| Failure {
        message: format!("transpile error: {e}"),
        stack: None,
        location: None,
    });
    timing::record_since(timing::Phase::Transpile, t_start);
    let out = out?;
    let sm = out
        .source_map
        .as_deref()
        .and_then(|j| sourcemap::SourceMap::from_slice(j.as_bytes()).ok());
    Ok((out.code, sm))
}

/// Evaluate the entry module; drain microtasks and surface any rejection as a
/// load `Failure` (no source-map remap, matching the load-error path).
fn evaluate_entry(ctx: &Ctx<'_>, entry_name: &str, src: &str) -> Result<(), Failure> {
    let promise = Module::evaluate(ctx.clone(), entry_name, src).map_err(|e| match e {
        Error::Exception => build_failure(capture_thrown(ctx), None),
        other => infra_failure(format!("entry declare error: {other}")),
    })?;
    drain(ctx);
    match promise.state() {
        PromiseState::Resolved => Ok(()),
        PromiseState::Rejected => {
            let _ = promise.result::<Value>();
            Err(build_failure(capture_thrown(ctx), None))
        }
        PromiseState::Pending => Err(infra_failure(
            "entry module still pending after draining jobs".to_string(),
        )),
    }
}

/// Re-import `zero/test` to read the describe tree the entry registered, by
/// stashing `__getTestTree__()` on `globalThis` and reading it back.
fn read_test_tree<'js>(ctx: &Ctx<'js>) -> Result<Object<'js>, Failure> {
    let probe = Module::evaluate(
        ctx.clone(),
        "__zero_test_tree_probe__",
        "import { __getTestTree__ } from 'zero/test';\
         globalThis.__ZERO_TEST_TREE__ = __getTestTree__();",
    )
    .map_err(|e| match e {
        Error::Exception => build_failure(capture_thrown(ctx), None),
        other => infra_failure(format!("test-tree probe error: {other}")),
    })?;
    drain(ctx);
    if probe.state() == PromiseState::Rejected {
        let _ = probe.result::<Value>();
        return Err(build_failure(capture_thrown(ctx), None));
    }
    ctx.globals()
        .get::<_, Object>("__ZERO_TEST_TREE__")
        .map_err(|_| infra_failure("zero/test did not produce a test tree".to_string()))
}

/// Serialize `globalThis.__zero_coverage__` (or `{}`) to a JSON value.
fn serialize_coverage(ctx: &Ctx<'_>) -> Option<serde_json::Value> {
    let cov = match ctx.globals().get::<_, Value>("__zero_coverage__") {
        Ok(v) if !v.is_undefined() && !v.is_null() => v,
        _ => ctx.eval::<Value, _>("({})").ok()?,
    };
    let json = ctx.json_stringify(cov).ok().flatten()?;
    let json = json.to_string().ok()?;
    serde_json::from_str::<serde_json::Value>(&json).ok()
}

/// Drain the QuickJS microtask queue until empty.
fn drain(ctx: &Ctx<'_>) {
    while ctx.execute_pending_job() {}
}

/// Recursively walk a describe node, running hooks and `it` bodies.
fn walk_describe<'js>(
    ctx: &Ctx<'js>,
    node: &Object<'js>,
    name_chain: &mut Vec<String>,
    outcomes: &mut Vec<TestOutcome>,
    sm: Option<&sourcemap::SourceMap>,
) {
    let before_all_failed = run_before_all(ctx, node);
    for child in get_children(node) {
        let fn_val: Option<Function> = child.get::<_, Option<Function>>("fn").ok().flatten();
        let child_name = get_string(&child, "name");
        if let Some(func) = fn_val {
            run_it_node(
                ctx,
                node,
                &func,
                child_name,
                name_chain,
                outcomes,
                before_all_failed.as_deref(),
                sm,
            );
        } else {
            name_chain.push(child_name);
            walk_describe(ctx, &child, name_chain, outcomes, sm);
            name_chain.pop();
        }
    }
    for hook in get_function_array(node, "afterAll") {
        let _ = call_and_drain(ctx, &hook);
    }
}

/// Run all `beforeAll` hooks on `node`. Returns `Some(reason)` if any threw —
/// the caller propagates this as a per-test skip reason.
fn run_before_all<'js>(ctx: &Ctx<'js>, node: &Object<'js>) -> Option<String> {
    for hook in get_function_array(node, "beforeAll") {
        if let Err(captured) = call_and_drain(ctx, &hook) {
            return Some(format!("beforeAll failed: {}", captured.message));
        }
    }
    None
}

/// Execute a single `it` node: run ancestor `beforeEach` hooks, the test body,
/// then `afterEach` hooks, and push the resulting `TestOutcome`.
#[allow(clippy::too_many_arguments)]
fn run_it_node<'js>(
    ctx: &Ctx<'js>,
    parent: &Object<'js>,
    func: &Function<'js>,
    child_name: String,
    name_chain: &mut Vec<String>,
    outcomes: &mut Vec<TestOutcome>,
    before_all_failed: Option<&str>,
    sm: Option<&sourcemap::SourceMap>,
) {
    name_chain.push(child_name);

    if let Some(reason) = before_all_failed {
        outcomes.push(TestOutcome {
            name_chain: name_chain.clone(),
            status: Status::Skipped(reason.to_string()),
            duration_ms: 0,
            failure: None,
        });
        name_chain.pop();
        return;
    }

    let before_each = get_function_array(parent, "beforeEach");
    let after_each = get_function_array(parent, "afterEach");

    let mut skip_reason: Option<String> = None;
    for hook in &before_each {
        if let Err(captured) = call_and_drain(ctx, hook) {
            skip_reason = Some(format!("beforeEach failed: {}", captured.message));
            break;
        }
    }

    let start = Instant::now();
    let result = if skip_reason.is_none() {
        call_and_drain(ctx, func)
    } else {
        Ok(())
    };
    let duration_ms = start.elapsed().as_millis();

    let (status, failure) = match (skip_reason, result) {
        (Some(reason), _) => (Status::Skipped(reason), None),
        (None, Ok(())) => (Status::Passed, None),
        (None, Err(captured)) => (Status::Failed, Some(build_failure(captured, sm))),
    };

    outcomes.push(TestOutcome {
        name_chain: name_chain.clone(),
        status,
        duration_ms,
        failure,
    });
    name_chain.pop();

    for hook in &after_each {
        let _ = call_and_drain(ctx, hook);
    }
}

/// Call `func` and drain microtasks; if it returned a promise, settle it.
/// Returns a `CapturedError` on a synchronous throw or a promise rejection.
fn call_and_drain<'js>(ctx: &Ctx<'js>, func: &Function<'js>) -> Result<(), CapturedError> {
    let mp: MaybePromise = match func.call::<_, MaybePromise>(()) {
        Ok(v) => v,
        Err(Error::Exception) => return Err(capture_thrown(ctx)),
        Err(e) => {
            return Err(CapturedError {
                message: format!("call error: {e}"),
                stack: None,
                user_frame: None,
            });
        }
    };
    loop {
        match mp.state() {
            PromiseState::Resolved => return Ok(()),
            PromiseState::Rejected => {
                let _ = mp.result::<Value>();
                return Err(capture_thrown(ctx));
            }
            PromiseState::Pending => {
                // Drive microtasks; if the queue empties with the promise still
                // pending, treat the body as settled (nothing left to run).
                if !ctx.execute_pending_job() {
                    return Ok(());
                }
            }
        }
    }
}

/// Capture the currently-thrown JS value (`Ctx::catch`) as a `CapturedError`.
fn capture_thrown(ctx: &Ctx<'_>) -> CapturedError {
    capture_from_value(ctx.catch())
}

/// Pull `message` (coerced like `String(v)`), `.stack`, and `._userFrame` off a
/// thrown JS value. Missing fields become `None`.
fn capture_from_value(val: Value<'_>) -> CapturedError {
    let message = val
        .get::<Coerced<String>>()
        .map(|c| c.0)
        .unwrap_or_else(|_| "<non-string error>".to_string());
    let (stack, user_frame) = match val.as_object() {
        Some(obj) => {
            let stack = obj
                .get::<_, Option<Coerced<String>>>("stack")
                .ok()
                .flatten()
                .map(|c| c.0);
            let user_frame = obj
                .get::<_, Option<Coerced<String>>>("_userFrame")
                .ok()
                .flatten()
                .map(|c| c.0);
            (stack, user_frame)
        }
        None => (None, None),
    };
    CapturedError {
        message,
        stack,
        user_frame,
    }
}

/// Turn a `CapturedError` into a `Failure` with source-mapped message, stack,
/// and location. Prefers the JS-side `_userFrame` over a parsed stack walk.
pub(crate) fn build_failure(captured: CapturedError, sm: Option<&sourcemap::SourceMap>) -> Failure {
    let message = remap_positions(&captured.message, sm);
    let stack = captured.stack.as_deref().map(|s| remap_positions(s, sm));
    let location = compute_location(captured.user_frame.as_deref(), stack.as_deref(), sm);
    Failure {
        message,
        stack,
        location,
    }
}

/// Choose a source location: prefer remapped `user_frame`, otherwise walk the
/// already-remapped stack for the first user-code frame.
///
/// The walk passes over framework-internal paths via [`is_user_path`], then
/// also skips frames whose function name appears in
/// [`FRAMEWORK_REGISTRATION_NAMES`] — those are calls that *contain* the
/// throw (e.g. `it(...)`), not the throw site itself. If no frame survives
/// both filters, the walker falls back to the first non-internal frame so
/// callers never lose a location they would have had under the old logic.
fn compute_location(
    user_frame: Option<&str>,
    remapped_stack: Option<&str>,
    sm: Option<&sourcemap::SourceMap>,
) -> Option<SourceLoc> {
    if let Some(uf) = user_frame {
        let remapped = remap_positions(uf, sm);
        if let Some(loc) = parse_simple_frame(&remapped)
            && is_user_path(&loc.file.to_string_lossy())
        {
            // Only trust a `_userFrame` that points at user code. Under QuickJS
            // the JS matcher can mis-capture its own `zero/test` frame; gating
            // here makes us fall through to the stack walk (which correctly
            // skips framework frames).
            return Some(loc);
        }
    }
    let stack_text = remapped_stack?;
    let mut fallback: Option<SourceLoc> = None;
    for line in stack_text.lines() {
        let Some((fn_name, path, l, c)) = parse_stack_frame(line) else {
            continue;
        };
        if !is_user_path(&path) {
            continue;
        }
        let loc = SourceLoc {
            file: PathBuf::from(&path),
            line: l,
            column: c,
        };
        let is_registration = fn_name
            .as_deref()
            .map(|n| FRAMEWORK_REGISTRATION_NAMES.contains(&n))
            .unwrap_or(false);
        if !is_registration {
            return Some(loc);
        }
        if fallback.is_none() {
            fallback = Some(loc);
        }
    }
    fallback
}

/// Parse a `"path:line:col"` string into a [`SourceLoc`].
fn parse_simple_frame(s: &str) -> Option<SourceLoc> {
    let re = regex::Regex::new(r"^(.+):(\d+):(\d+)$").ok()?;
    let caps = re.captures(s)?;
    Some(SourceLoc {
        file: PathBuf::from(&caps[1]),
        line: caps[2].parse().ok()?,
        column: caps[3].parse().ok()?,
    })
}

/// Parse a single stack-trace line into `(fn_name, path, line, column)`.
/// Accepts V8 `"    at fn (path:L:C)"`, SpiderMonkey `"fn@path:L:C"`, and
/// plain `"path:L:C"`. `fn_name` is `None` for plain frames or when the
/// format provides no function name.
fn parse_stack_frame(line: &str) -> Option<(Option<String>, String, u32, u32)> {
    let re = regex::Regex::new(r"(?:\(|@|\s)([^\s()@]+):(\d+):(\d+)\)?\s*$").ok()?;
    let caps = re.captures(line)?;
    let path = caps[1].to_string();
    let l: u32 = caps[2].parse().ok()?;
    let c: u32 = caps[3].parse().ok()?;
    let fn_name = extract_fn_name(line);
    Some((fn_name, path, l, c))
}

/// Pull the function name from a stack frame line.
/// V8 `"    at NAME (path:...)"` → `Some(NAME)`.
/// SpiderMonkey `"NAME@path:..."` → `Some(NAME)`.
/// `"    at path:..."` (no function name) or plain `"path:..."` → `None`.
fn extract_fn_name(line: &str) -> Option<String> {
    let v8 = regex::Regex::new(r"^\s*at\s+([^\s(]+)\s+\(").ok()?;
    if let Some(caps) = v8.captures(line) {
        return Some(caps[1].to_string());
    }
    let sm = regex::Regex::new(r"^([^@\s][^@]*?)@").ok()?;
    if let Some(caps) = sm.captures(line) {
        return Some(caps[1].to_string());
    }
    None
}

/// Returns true if `path` points at user code (not a framework-internal module
/// nor a `node:`-prefixed pseudo-module).
fn is_user_path(path: &str) -> bool {
    if path.starts_with("node:") {
        return false;
    }
    // The QuickJS engine names the in-memory runtime modules by their bare
    // specifier (e.g. `zero/test`), so they surface in stack frames as such
    // rather than as `*.js` basenames. Treat them as framework-internal.
    if QJS_RUNTIME_MODULE_NAMES.contains(&path) {
        return false;
    }
    let base = path.rsplit_once('/').map(|(_, b)| b).unwrap_or(path);
    !FRAMEWORK_INTERNAL_BASENAMES.contains(&base)
}

/// In-memory runtime module names used as QuickJS stack-frame paths.
const QJS_RUNTIME_MODULE_NAMES: &[&str] = &["zero", "zero/test", "zero/http", "zero/components"];

// ---------------------------------------------------------------------------
// JS value helpers (rquickjs Object/Array access)
// ---------------------------------------------------------------------------

/// Read a string property, coercing like `String(node[key])`; `""` if absent.
fn get_string<'js>(node: &Object<'js>, key: &str) -> String {
    node.get::<_, Option<Coerced<String>>>(key)
        .ok()
        .flatten()
        .map(|c| c.0)
        .unwrap_or_default()
}

/// Read an array-of-functions property (hooks). Non-array or absent → empty.
fn get_function_array<'js>(node: &Object<'js>, key: &str) -> Vec<Function<'js>> {
    match node.get::<_, Option<Array<'js>>>(key) {
        Ok(Some(arr)) => (0..arr.len())
            .filter_map(|i| arr.get::<Function<'js>>(i).ok())
            .collect(),
        _ => vec![],
    }
}

/// Read the `children` array as objects (describe or it nodes).
fn get_children<'js>(node: &Object<'js>) -> Vec<Object<'js>> {
    match node.get::<_, Option<Array<'js>>>("children") {
        Ok(Some(arr)) => (0..arr.len())
            .filter_map(|i| arr.get::<Value<'js>>(i).ok())
            .filter_map(|v| v.into_object())
            .collect(),
        _ => vec![],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write as _;
    use tempfile::NamedTempFile;

    thread_local! {
        static FORCE_TEARDOWN_PANIC: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
    }

    /// Read the thread-local teardown-panic flag from inside the harness.
    /// Always `false` in production builds (the module isn't compiled).
    pub(super) fn should_force_teardown_panic() -> bool {
        FORCE_TEARDOWN_PANIC.with(|cell| cell.get())
    }

    struct ForceTeardownPanicGuard;

    impl ForceTeardownPanicGuard {
        fn install() -> Self {
            FORCE_TEARDOWN_PANIC.with(|cell| cell.set(true));
            Self
        }
    }

    impl Drop for ForceTeardownPanicGuard {
        fn drop(&mut self) {
            FORCE_TEARDOWN_PANIC.with(|cell| cell.set(false));
        }
    }

    fn write_temp_js(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::with_suffix(".js").unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    fn write_temp_ts(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::with_suffix(".test.ts").unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    #[test]
    fn run_file_handles_ts_entry() {
        let f = write_temp_ts(
            r#"import { describe, it, expect } from "zero/test";
const n: number = 1;
describe("g", () => { it("ok", () => expect(n).toBe(1)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn passing_test_produces_passed_outcome() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => { it("ok", () => expect(1).toBe(1)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].name_chain, vec!["g", "ok"]);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn run_file_with_coverage_returns_coverage_snapshot() {
        use crate::coverage::CoverageScope;
        use crate::loader::CoverageContext;

        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("src")).unwrap();
        std::fs::write(
            root.join("src").join("foo.ts"),
            "export function bar(){ return 42 }\n",
        )
        .unwrap();
        let test_path = root.join("foo.test.ts");
        std::fs::write(
            &test_path,
            r#"import { describe, it, expect } from "zero/test";
import { bar } from "./src/foo.ts";
describe("g", () => { it("works", () => expect(bar()).toBe(42)); });
"#,
        )
        .unwrap();

        let scope = CoverageScope::new(root.to_path_buf(), root.join("dist"));
        let ctx = Rc::new(CoverageContext::new(scope));
        let outcome = run_file_with_coverage(root, &test_path, Some(ctx.clone()));
        assert!(
            outcome.result.load_error.is_none(),
            "load_error: {:?}",
            outcome.result.load_error
        );
        assert_eq!(outcome.result.outcomes.len(), 1);
        let cov = outcome.coverage.expect("coverage snapshot present");
        let maps = ctx.drain_maps();
        assert!(!maps.is_empty(), "expected at least one instrumented file");
        // The snapshot should include the foo.ts file with bar fn hit.
        let foo_key = maps[0].file.to_string_lossy().to_string();
        let bar_hits = cov
            .get(&foo_key)
            .and_then(|v| v.get("fns"))
            .and_then(|v| v.get("bar"))
            .and_then(|v| v.as_u64())
            .unwrap_or(0);
        assert_eq!(bar_hits, 1, "expected fns.bar=1, snapshot: {cov}");
    }

    #[test]
    fn failing_assertion_carries_location() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => { it("fail", () => expect(1).toBe(2)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        let failure = result.outcomes[0]
            .failure
            .as_ref()
            .expect("failure present");
        let loc = failure.location.as_ref().expect("location should be Some");
        let expected_file = f.path();
        assert_eq!(
            loc.file, expected_file,
            "loc.file did not match temp test path; stack: {:?}",
            failure.stack
        );
        assert!(loc.line >= 1);
        assert!(loc.column >= 1);
    }

    #[test]
    fn load_error_top_level_throw_degrades_gracefully_to_no_location() {
        // A top-level `throw new Error(...)` surfaces as a load error: the
        // user-facing message is preserved, and `location` may be None (the
        // reporter then falls back to the message-only path). This test pins
        // that contract — the message must survive regardless of location.
        let f = write_temp_js(
            r#"import { describe } from "zero/test";
function boom() { throw new Error("nope at top"); }
boom();
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        let le = result.load_error.expect("expected load_error");
        assert!(
            le.message.contains("nope at top"),
            "message should preserve user-thrown text: {:?}",
            le.message
        );
        // location is allowed to be None here; verifying that no panic / error
        // is reached and the path still surfaces the message is enough.
        let _ = le.location;
    }

    #[test]
    fn location_skips_runtime_frames() {
        // The matcher frames (zero/test internal) are in the stack between the
        // throw site and the user call; the picked location must point at the
        // user file, not at the matcher.
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
function callsite() { expect(1).toBe(2); }
describe("g", () => { it("fail", () => callsite()); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        let failure = result.outcomes[0].failure.as_ref().expect("failure");
        let loc = failure.location.as_ref().expect("location");
        assert_eq!(loc.file, f.path());
        // `callsite` body is on line 2 — assert at least we point at the user file
        // and a plausible line (1..=3 covers any minor numbering variance).
        assert!(
            (1..=3).contains(&loc.line),
            "loc.line should be inside the user file's first few lines, got {} (stack: {:?})",
            loc.line,
            failure.stack
        );
    }

    #[test]
    fn failing_assertion_produces_failed_outcome() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => { it("fail", () => expect(1).toBe(2)); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Failed);
        let msg = result.outcomes[0].failure.as_ref().unwrap().message.clone();
        assert!(msg.contains('1') && msg.contains('2'), "message: {msg}");
    }

    #[test]
    fn top_level_throw_sets_load_error() {
        let f = write_temp_js(
            r#"import { describe } from "zero/test";
throw new Error("nope");
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_some(), "expected load_error");
        assert!(result.outcomes.is_empty());
    }

    #[test]
    fn failing_before_each_skips_subsequent_its() {
        let f = write_temp_js(
            r#"import { describe, it, beforeEach, expect } from "zero/test";
describe("g", () => {
  beforeEach(() => { throw new Error("oh no"); });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            assert!(
                matches!(o.status, Status::Skipped(_)),
                "expected Skipped, got {:?} for {}",
                o.status,
                o.name_chain.join(" > ")
            );
        }
    }

    #[test]
    fn document_root_props_are_writable_for_isolation() {
        // Regression: `document.documentElement` / `head` / `body` were
        // getter-only, so a `beforeEach` that swaps them for isolation threw
        // "cannot set non-writable property" and the test was silently
        // reported as Skipped. They now have setters, so the swap succeeds and
        // the test runs to a real Pass/Fail. Mirrors the demo's Layout.test.ts
        // theme-isolation pattern (swap the root, assert a setAttribute write,
        // restore in afterEach).
        let f = write_temp_js(
            r#"import { describe, it, beforeEach, afterEach, expect } from "zero/test";
function fakeRoot() {
  const attrs = new Map();
  return {
    setAttribute: (k, v) => void attrs.set(k, v),
    getAttribute: (k) => (attrs.has(k) ? attrs.get(k) : null),
  };
}
describe("root isolation", () => {
  let savedEl, savedHead, savedBody;
  beforeEach(() => {
    savedEl = document.documentElement;
    savedHead = document.head;
    savedBody = document.body;
    document.documentElement = fakeRoot();
    document.head = fakeRoot();
    document.body = fakeRoot();
  });
  afterEach(() => {
    document.documentElement = savedEl;
    document.head = savedHead;
    document.body = savedBody;
  });
  it("captures writes on the swapped root", () => {
    document.documentElement.setAttribute("data-theme", "dark");
    expect(document.documentElement.getAttribute("data-theme")).toBe("dark");
  });
  it("swaps head and body too", () => {
    document.head.setAttribute("x", "1");
    document.body.setAttribute("y", "2");
    expect(document.head.getAttribute("x")).toBe("1");
    expect(document.body.getAttribute("y")).toBe("2");
  });
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none(), "unexpected load error");
        for o in &result.outcomes {
            assert!(
                matches!(o.status, Status::Passed),
                "expected Passed, got {:?} for {}",
                o.status,
                o.name_chain.join(" > ")
            );
        }
        assert_eq!(result.outcomes.len(), 2, "expected both its to run");
    }

    #[test]
    fn parse_simple_frame_extracts_components() {
        let loc = super::parse_simple_frame("/path/to/a.js:12:34").unwrap();
        assert_eq!(loc.file, PathBuf::from("/path/to/a.js"));
        assert_eq!(loc.line, 12);
        assert_eq!(loc.column, 34);
    }

    #[test]
    fn parse_simple_frame_returns_none_when_missing_position() {
        assert!(super::parse_simple_frame("/path/no/position.js").is_none());
    }

    #[test]
    fn parse_stack_frame_accepts_v8_format() {
        let got = super::parse_stack_frame("    at fn (/x/a.js:1:2)").unwrap();
        assert_eq!(got, (Some("fn".to_string()), "/x/a.js".to_string(), 1, 2));
    }

    #[test]
    fn parse_stack_frame_accepts_spidermonkey_format() {
        let got = super::parse_stack_frame("fn@/x/a.js:3:4").unwrap();
        assert_eq!(got, (Some("fn".to_string()), "/x/a.js".to_string(), 3, 4));
    }

    #[test]
    fn parse_stack_frame_returns_none_on_garbage() {
        assert!(super::parse_stack_frame("definitely not a frame").is_none());
    }

    #[test]
    fn parse_stack_frame_v8_no_function_name() {
        // V8 "    at path:L:C" frames have no function name.
        let got = super::parse_stack_frame("    at /x/a.js:5:6").unwrap();
        assert_eq!(got, (None, "/x/a.js".to_string(), 5, 6));
    }

    #[test]
    fn parse_stack_frame_extracts_registration_name() {
        let got = super::parse_stack_frame("    at it (/x/test.js:42:7)").unwrap();
        assert_eq!(
            got,
            (Some("it".to_string()), "/x/test.js".to_string(), 42, 7)
        );
    }

    #[test]
    fn is_user_path_rejects_node_prefix() {
        assert!(!super::is_user_path("node:internal/process/task_queues"));
    }

    #[test]
    fn is_user_path_rejects_framework_internal_basenames() {
        assert!(!super::is_user_path("/foo/test.js"));
        assert!(!super::is_user_path("/foo/template.js"));
        assert!(!super::is_user_path("/foo/reactivity.js"));
        assert!(!super::is_user_path("/foo/app.js"));
        assert!(!super::is_user_path("/foo/router.js"));
        assert!(!super::is_user_path("/foo/dom-shim.js"));
        assert!(!super::is_user_path("/foo/http.js"));
    }

    #[test]
    fn is_user_path_accepts_user_modules() {
        assert!(super::is_user_path("/x/src/app.test.js"));
        assert!(super::is_user_path("/x/src/home.ts"));
        assert!(super::is_user_path("just_a_bare_name.js"));
    }

    #[test]
    fn compute_location_prefers_user_frame_over_stack() {
        let user = Some("/x/src/a.ts:1:2");
        let stack = Some("at thing (/x/src/other.ts:5:6)");
        let loc = super::compute_location(user, stack, None).unwrap();
        assert_eq!(loc.file, PathBuf::from("/x/src/a.ts"));
        assert_eq!(loc.line, 1);
    }

    #[test]
    fn compute_location_walks_stack_when_no_user_frame() {
        // First framework frame is skipped, second user frame is picked.
        let stack = Some("at h (/x/src/template.js:1:2)\nat g (/x/src/user.ts:3:4)");
        let loc = super::compute_location(None, stack, None).unwrap();
        assert_eq!(loc.file, PathBuf::from("/x/src/user.ts"));
        assert_eq!(loc.line, 3);
        assert_eq!(loc.column, 4);
    }

    #[test]
    fn compute_location_returns_none_when_no_user_frame_anywhere() {
        let stack = Some("at h (/x/src/template.js:1:2)\nat g (/x/src/app.js:3:4)");
        assert!(super::compute_location(None, stack, None).is_none());
    }

    #[test]
    fn compute_location_returns_none_when_no_input() {
        assert!(super::compute_location(None, None, None).is_none());
    }

    #[test]
    fn compute_location_skips_user_it_registration_frame() {
        // The `it()` registration frame is in user code (test.test.js) but
        // it's not the throw site — the throw happens inside the body that
        // `it` wraps. Walker should skip past `it` and pick the next frame.
        let stack = Some(
            "at it (/x/src/a.test.ts:10:5)\n\
             at body (/x/src/a.test.ts:3:11)",
        );
        let loc = super::compute_location(None, stack, None).unwrap();
        assert_eq!(loc.line, 3);
        assert_eq!(loc.column, 11);
    }

    #[test]
    fn compute_location_falls_back_to_registration_when_no_other_frame() {
        // No other user frames; the registration frame is all we have.
        // Don't return None — better wrong than empty.
        let stack = Some("at it (/x/src/a.test.ts:10:5)");
        let loc = super::compute_location(None, stack, None).unwrap();
        assert_eq!(loc.line, 10);
    }

    #[test]
    fn compute_location_skips_describe_render_cleanup_frames() {
        for fn_name in ["describe", "render", "cleanup", "beforeEach"] {
            let stack_str = format!(
                "at {fn_name} (/x/src/a.test.ts:10:5)\n\
                 at body (/x/src/a.test.ts:7:9)",
            );
            let loc = super::compute_location(None, Some(&stack_str), None).unwrap();
            assert_eq!(loc.line, 7, "{fn_name} should be skipped");
        }
    }

    #[test]
    fn remap_positions_passthrough_without_sourcemap() {
        let s = "at f (/x/a.ts:5:7)";
        assert_eq!(super::remap_positions(s, None), s);
    }

    #[test]
    fn nested_describe_blocks_walk_in_order() {
        let f = write_temp_js(
            r#"import { describe, it, expect } from "zero/test";
describe("outer", () => {
  it("o-a", () => expect(1).toBe(1));
  describe("inner", () => {
    it("i-a", () => expect(2).toBe(2));
    it("i-b", () => expect(3).toBe(3));
  });
  it("o-b", () => expect(4).toBe(4));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        let names: Vec<_> = result
            .outcomes
            .iter()
            .map(|o| o.name_chain.join(" > "))
            .collect();
        assert!(names.contains(&"outer > o-a".to_string()), "{names:?}");
        assert!(
            names.contains(&"outer > inner > i-a".to_string()),
            "{names:?}"
        );
        assert!(
            names.contains(&"outer > inner > i-b".to_string()),
            "{names:?}"
        );
        assert!(names.contains(&"outer > o-b".to_string()), "{names:?}");
    }

    #[test]
    fn before_all_failure_skips_all_its_with_reason() {
        let f = write_temp_js(
            r#"import { describe, it, beforeAll, expect } from "zero/test";
describe("g", () => {
  beforeAll(() => { throw new Error("boot failure"); });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            match &o.status {
                Status::Skipped(reason) => assert!(reason.contains("beforeAll")),
                other => panic!("expected Skipped, got {other:?}"),
            }
        }
    }

    #[test]
    fn after_each_runs_even_after_test_failure() {
        let f = write_temp_js(
            r#"import { describe, it, afterEach, expect } from "zero/test";
let tail = [];
describe("g", () => {
  afterEach(() => { tail.push("ae"); });
  it("fail", () => expect(1).toBe(2));
  it("pass", () => { expect(tail.length).toBe(1); });
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        let pass = result
            .outcomes
            .iter()
            .find(|o| o.name_chain.iter().any(|n| n == "pass"))
            .unwrap();
        assert!(matches!(pass.status, Status::Passed));
    }

    #[test]
    fn top_level_it_without_describe_runs() {
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("lone", () => expect(1).toBe(1));
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].name_chain, vec!["lone".to_string()]);
        assert!(matches!(result.outcomes[0].status, Status::Passed));
    }

    #[test]
    fn async_test_awaits_promise_resolution() {
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("awaits", async () => {
  await Promise.resolve();
  expect(2 + 2).toBe(4);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert!(matches!(result.outcomes[0].status, Status::Passed));
    }

    #[test]
    fn async_test_rejection_is_a_failure() {
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("rejects", async () => { throw new Error("rejected"); });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert!(matches!(result.outcomes[0].status, Status::Failed));
    }

    #[test]
    fn after_all_runs_after_all_its() {
        let f = write_temp_js(
            r#"import { describe, it, afterAll, expect } from "zero/test";
globalThis.afterAllCount = 0;
describe("g", () => {
  afterAll(() => { globalThis.afterAllCount++; });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            assert!(matches!(o.status, Status::Passed));
        }
    }

    #[test]
    fn console_log_in_test_does_not_crash() {
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("logs", () => {
  console.log("hello");
  console.warn("warn");
  console.error("err");
  expect(1).toBe(1);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        assert!(matches!(result.outcomes[0].status, Status::Passed));
    }

    #[test]
    fn map_using_test_runs_clean() {
        // A test file using `Map` — the case that crashed the previous engine's
        // GC finalizer. QuickJS runs it and drops cleanly.
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("uses a Map", () => {
  const m = new Map();
  m.set("a", 1);
  expect(m.get("a")).toBe(1);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn throwing_non_error_value_still_produces_failed_outcome() {
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("throws-string", () => { throw "literal string"; });
it("throws-number", () => { throw 42; });
it("throws-object", () => { throw { code: "X" }; });
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        for o in &result.outcomes {
            assert!(matches!(o.status, Status::Failed));
        }
    }

    #[test]
    fn multiple_files_independent_test_state() {
        let f1 = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("alpha", () => expect(1).toBe(1));
"#,
        );
        let f2 = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("beta", () => expect(2).toBe(2));
"#,
        );
        let r1 = run_file(f1.path().parent().unwrap(), f1.path());
        let r2 = run_file(f2.path().parent().unwrap(), f2.path());
        assert_eq!(r1.outcomes.len(), 1);
        assert_eq!(r1.outcomes[0].name_chain, vec!["alpha".to_string()]);
        assert_eq!(r2.outcomes.len(), 1);
        assert_eq!(r2.outcomes[0].name_chain, vec!["beta".to_string()]);
    }

    #[test]
    fn raw_typeerror_reports_throw_line_not_it_line() {
        // A test body that throws a raw TypeError (no matcher _userFrame
        // decoration). The harness should attribute the failure to the
        // throw site, not to the `it(...)` registration line.
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("raw throw", () => {
  const obj = null;
  obj.foo;
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        let failure = result.outcomes[0]
            .failure
            .as_ref()
            .expect("expected failure");
        if let Some(loc) = failure.location.as_ref() {
            // `it(...)` is on line 2; the throw site is on line 4.
            // The registration filter should keep us off line 2.
            assert_ne!(
                loc.line, 2,
                "location should not point at the it() registration line; stack: {:?}",
                failure.stack
            );
        }
    }

    #[test]
    fn explicit_throw_in_test_body_reports_throw_line() {
        let f = write_temp_js(
            r#"import { it } from "zero/test";
it("explicit throw", () => {
  throw new Error("boom");
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 1);
        let failure = result.outcomes[0]
            .failure
            .as_ref()
            .expect("expected failure");
        assert!(failure.message.contains("boom"));
        if let Some(loc) = failure.location.as_ref() {
            assert_ne!(
                loc.line, 2,
                "location should not point at the it() registration line; stack: {:?}",
                failure.stack
            );
        }
    }

    #[test]
    fn matcher_failure_still_points_at_matcher_call() {
        // Regression: matcher failures already had a useful location.
        // The new registration filter must not regress this path.
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("matcher fail", () => {
  expect(1).toBe(2);
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        let failure = result.outcomes[0].failure.as_ref().expect("failure");
        let loc = failure.location.as_ref().expect("location");
        // The matcher call is on line 3.
        assert_eq!(
            loc.line, 3,
            "matcher location should point at the expect() call; stack: {:?}",
            failure.stack
        );
    }

    #[test]
    fn forced_teardown_panic_becomes_structured_failure() {
        // Drive the test-only thread-local trigger to exercise the
        // catch_unwind path: the harness must convert the panic into a
        // synthetic Failed outcome rather than crashing the test process.
        let f = write_temp_js(
            r#"import { it, expect } from "zero/test";
it("ok", () => expect(1).toBe(1));
"#,
        );
        let root = f.path().parent().unwrap();
        let _guard = ForceTeardownPanicGuard::install();
        let result = run_file(root, f.path());
        drop(_guard);
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1, "expected one synthetic outcome");
        let outcome = &result.outcomes[0];
        assert!(matches!(outcome.status, Status::Failed));
        let failure = outcome.failure.as_ref().expect("expected failure");
        assert!(
            failure.message.contains("panic during teardown"),
            "message should mention the teardown panic, got: {}",
            failure.message
        );
        assert!(
            outcome.name_chain.iter().any(|n| n.contains("teardown")),
            "name should mention teardown: {:?}",
            outcome.name_chain
        );
    }

    #[test]
    fn after_each_failure_does_not_break_subsequent_its() {
        let f = write_temp_js(
            r#"import { describe, it, afterEach, expect } from "zero/test";
describe("g", () => {
  afterEach(() => { throw new Error("cleanup blew up"); });
  it("a", () => expect(1).toBe(1));
  it("b", () => expect(2).toBe(2));
});
"#,
        );
        let root = f.path().parent().unwrap();
        let result = run_file(root, f.path());
        assert!(result.load_error.is_none());
        assert_eq!(result.outcomes.len(), 2);
        // Both 'a' and 'b' should still have been recorded.
        for o in &result.outcomes {
            assert!(matches!(o.status, Status::Passed));
        }
    }

    #[test]
    fn read_workspace_file_returns_contents() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("known-file.txt"), "hello-from-workspace").unwrap();
        let test_path = root.join("read.test.js");
        std::fs::write(
            &test_path,
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => {
  it("reads workspace file", () => {
    const s = globalThis.__readWorkspaceFile__("known-file.txt");
    expect(s).toContain("hello-from-workspace");
  });
});
"#,
        )
        .unwrap();
        let result = run_file(root, &test_path);
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }

    #[test]
    fn read_workspace_file_rejects_escaping_path() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let test_path = root.join("escape.test.js");
        std::fs::write(
            &test_path,
            r#"import { describe, it, expect } from "zero/test";
describe("g", () => {
  it("rejects escape", () => {
    expect(() => globalThis.__readWorkspaceFile__("../outside")).toThrow();
  });
});
"#,
        )
        .unwrap();
        let result = run_file(root, &test_path);
        assert!(
            result.load_error.is_none(),
            "load_error: {:?}",
            result.load_error
        );
        assert_eq!(result.outcomes.len(), 1);
        assert_eq!(result.outcomes[0].status, Status::Passed);
    }
}
